In [14]:
import pandas as pd
import os
import numpy as np

In [2]:
import pkg_resources
import types
def get_imports():
    for name, val in globals().items():
        if isinstance(val, types.ModuleType):
            # Split ensures you get root package, 
            # not just imported function
            name = val.__name__.split(".")[0]

        elif isinstance(val, type):
            name = val.__module__.split(".")[0]

        # Some packages are weird and have different
        # imported names vs. system/pip names. Unfortunately,
        # there is no systematic way to get pip names from
        # a package's imported name. You'll have to add
        # exceptions to this list manually!
        poorly_named_packages = {
            "PIL": "Pillow",
            "sklearn": "scikit-learn"
        }
        if name in poorly_named_packages.keys():
            name = poorly_named_packages[name]

        yield name
imports = list(set(get_imports()))

# The only way I found to get the version of the root package
# from only the name of the package is to cross-check the names 
# of installed packages vs. imported packages
requirements = []
for m in pkg_resources.working_set:
    if m.project_name in imports and m.project_name!="pip":
        requirements.append((m.project_name, m.version))

for r in requirements:
    print("{}=={}".format(*r))

pandas==1.5.1

In [3]:
path_original_data = r'C:\Users\heldi\Downloads\Coding\Projects\DNA_Encodings\Data\Original'
size_df = pd.DataFrame(columns=['Filename', 'Size'])
for file_name in os.listdir(path_original_data):
    path = os.path.join(path_original_data, file_name)
    size = os.path.getsize(path)
    file_name1 = os.path.splitext(file_name)[0]
    list = [file_name1, size]
    size_df.loc[len(size_df)] = list
size_df

                          Filename     Size
0                    Anna_Karenina  2068079
1  Around_the_World_in_Eighty_Days   403521
2                        bbc_house  2248808
3             bbc_peregrine_falcon   751800
4                      La_Jeunesse    26329
5       The_Picture_of_Dorian_Gray   465592
6               The_Republic_Plato  1243940
7                          Ulysses  1586336
8            Vue_de_la_Buena_Vista    70296

In [4]:
df_measure = pd.read_pickle(r"data/pre_measure.pkl")

In [5]:
df_measure

,Filename,Method,Transformation,Size,Cost,Time,Type,OriFile_Size
0,Anna_Karenina,Repetition Code,Encoding,48555234,48555234,24.537284,.txt,2068079
1,Anna_Karenina,Repetition Code,Decoding,128,0,69.430668,.txt,2068079
2,Anna_Karenina,Simple Code,Encoding,1031274,1031274,1.087373,.txt,2068079
3,Anna_Karenina,Simple Code,Decoding,622784,622656,0.113236,.txt,2068079
4,Anna_Karenina,XOR-Based Code,Encoding,58610340,58610340,2.004188,.txt,2068079
...,...,...,...,...,...,...,...,...
535,Vue_de_la_Buena_Vista,Repetition Code,Decoding,128,0,2.335622,.jpg,70296
536,Vue_de_la_Buena_Vista,Simple Code,Encoding,931581,931581,1.268053,.jpg,70296
537,Vue_de_la_Buena_Vista,Simple Code,Decoding,562592,562464,0.148494,.jpg,70296
538,Vue_de_la_Buena_Vista,XOR-Based Code,Encoding,1997605,1997605,0.068561,.jpg,70296
539,Vue_de_la_Buena_Vista,XOR-Based Code,Decoding,562496,562368,0.230991,.jpg,70296

In [6]:
list = []
for filename in df_measure['Filename']:
    index = size_df.index[size_df['Filename'] == filename]
    size = size_df['Size'].iloc[index].values[0]
    list.append(size)
list

[2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296]

In [7]:
df_measure['OriFile_Size']=list

In [8]:
df_measure

,Filename,Method,Transformation,Size,Cost,Time,Type,OriFile_Size
0,Anna_Karenina,Repetition Code,Encoding,48555234,48555234,24.537284,.txt,2068079
1,Anna_Karenina,Repetition Code,Decoding,128,0,69.430668,.txt,2068079
2,Anna_Karenina,Simple Code,Encoding,1031274,1031274,1.087373,.txt,2068079
3,Anna_Karenina,Simple Code,Decoding,622784,622656,0.113236,.txt,2068079
4,Anna_Karenina,XOR-Based Code,Encoding,58610340,58610340,2.004188,.txt,2068079
...,...,...,...,...,...,...,...,...
535,Vue_de_la_Buena_Vista,Repetition Code,Decoding,128,0,2.335622,.jpg,70296
536,Vue_de_la_Buena_Vista,Simple Code,Encoding,931581,931581,1.268053,.jpg,70296
537,Vue_de_la_Buena_Vista,Simple Code,Decoding,562592,562464,0.148494,.jpg,70296
538,Vue_de_la_Buena_Vista,XOR-Based Code,Encoding,1997605,1997605,0.068561,.jpg,70296
539,Vue_de_la_Buena_Vista,XOR-Based Code,Decoding,562496,562368,0.230991,.jpg,70296

In [38]:
df_measure.to_pickle('data/pre_measure.pkl')

In [11]:
df_agg = df_measure.groupby(['Filename', 'Method', 'Transformation', 'Type', 'OriFile_Size']).agg({'Size': ['mean', 'median', 'min', 'max', 'count', 'std'],'Time': ['mean', 'median', 'min', 'max', 'count', 'std'],'Cost': ['mean', 'median', 'min', 'max', 'count', 'std']}).reset_index()

In [12]:
df_agg

                           Filename           Method Transformation  Type  \

0                     Anna_Karenina  Repetition Code       Decoding  .txt
1                     Anna_Karenina  Repetition Code       Encoding  .txt
2                     Anna_Karenina      Simple Code       Decoding  .txt
3                     Anna_Karenina      Simple Code       Encoding  .txt
4                     Anna_Karenina   XOR-Based Code       Decoding  .txt
5                     Anna_Karenina   XOR-Based Code       Encoding  .txt
6   Around_the_World_in_Eighty_Days  Repetition Code       Decoding  .txt
7   Around_the_World_in_Eighty_Days  Repetition Code       Encoding  .txt
8   Around_the_World_in_Eighty_Days      Simple Code       Decoding  .txt
9   Around_the_World_in_Eighty_Days      Simple Code       Encoding  .txt
10  Around_the_World_in_Eighty_Days   XOR-Based Code       Decoding  .txt
11  Around_the_World_in_Eighty_Days   XOR-Based Code       Encoding  .txt
12                      La_Jeunesse  Repetition Code       Decoding  .jpg
13                      La_Jeunesse  Repetition Code       Encoding  .jpg
14                      La_Jeunesse      Simple Code       Decoding  .jpg
15                      La_Jeunesse      Simple Code       Encoding  .jpg
16                      La_Jeunesse   XOR-Based Code       Decoding  .jpg
17                      La_Jeunesse   XOR-Based Code       Encoding  .jpg
18       The_Picture_of_Dorian_Gray  Repetition Code       Decoding  .txt
19       The_Picture_of_Dorian_Gray  Repetition Code       Encoding  .txt
20       The_Picture_of_Dorian_Gray      Simple Code       Decoding  .txt
21       The_Picture_of_Dorian_Gray      Simple Code       Encoding  .txt
22       The_Picture_of_Dorian_Gray   XOR-Based Code       Decoding  .txt
23       The_Picture_of_Dorian_Gray   XOR-Based Code       Encoding  .txt
24               The_Republic_Plato  Repetition Code       Decoding  .txt
25               The_Republic_Plato  Repetition Code       Encoding  .txt
26               The_Republic_Plato      Simple Code       Decoding  .txt
27               The_Republic_Plato      Simple Code       Encoding  .txt
28               The_Republic_Plato   XOR-Based Code       Decoding  .txt
29               The_Republic_Plato   XOR-Based Code       Encoding  .txt
30                          Ulysses  Repetition Code       Decoding  .txt
31                          Ulysses  Repetition Code       Encoding  .txt
32                          Ulysses      Simple Code       Decoding  .txt
33                          Ulysses      Simple Code       Encoding  .txt
34                          Ulysses   XOR-Based Code       Decoding  .txt
35                          Ulysses   XOR-Based Code       Encoding  .txt
36            Vue_de_la_Buena_Vista  Repetition Code       Decoding  .jpg
37            Vue_de_la_Buena_Vista  Repetition Code       Encoding  .jpg
38            Vue_de_la_Buena_Vista      Simple Code       Decoding  .jpg
39            Vue_de_la_Buena_Vista      Simple Code       Encoding  .jpg
40            Vue_de_la_Buena_Vista   XOR-Based Code       Decoding  .jpg
41            Vue_de_la_Buena_Vista   XOR-Based Code       Encoding  .jpg
42                        bbc_house  Repetition Code       Decoding  .wav
43                        bbc_house  Repetition Code       Encoding  .wav
44                        bbc_house      Simple Code       Decoding  .wav
45                        bbc_house      Simple Code       Encoding  .wav
46                        bbc_house   XOR-Based Code       Decoding  .wav
47                        bbc_house   XOR-Based Code       Encoding  .wav
48             bbc_peregrine_falcon  Repetition Code       Decoding  .wav
49             bbc_peregrine_falcon  Repetition Code       Encoding  .wav
50             bbc_peregrine_falcon      Simple Code       Decoding  .wav
51             bbc_peregrine_falcon      Simple Code       Encoding  .wav
52             bbc_peregrine_falcon   XOR-Based Code       Decoding  .wav
53             bbc_peregrine_falcon   XOR-Based Code       Encoding  .wav

   OriFile_Size        Size                                        ...  \
                       mean      median       min       max count  ...
0       2068079       128.0       128.0       128       128    10  ...
1       2068079  48555234.0  48555234.0  48555234  48555234    10  ...
2       2068079    622784.0    622784.0    622784    622784    10  ...
3       2068079   1031274.0   1031274.0   1031274   1031274    10  ...
4       2068079  16544760.0  16544760.0  16544760  16544760    10  ...
5       2068079  58610340.0  58610340.0  58610340  58610340    10  ...
6        403521       128.0       128.0       128       128    10  ...
7        403521   9469746.0   9469746.0   9469746   9469746    10  ...
8        403521    622784.0    622784.0    622784    622784    10  ...
9        403521   1031274.0   1031274.0   1031274   1031274    10  ...
10       403521   3228296.0   3228296.0   3228296   3228296    10  ...
11       403521  11437647.0  11437647.0  11437647  11437647    10  ...
12        26329       128.0       128.0       128       128    10  ...
13        26329    624078.0    624078.0    624078    624078    10  ...
14        26329    210848.0    210848.0    210848    210848    10  ...
15        26329    349005.0    349005.0    349005    349005    10  ...
16        26329    210760.0    210760.0    210760    210760    10  ...
17        26329    749052.0    749052.0    749052    749052    10  ...
18       465592       128.0       128.0       128       128    10  ...
19       465592  10934586.0  10934586.0  10934586  10934586    10  ...
20       465592    622784.0    622784.0    622784    622784    10  ...
21       465592   1031274.0   1031274.0   1031274   1031274    10  ...
22       465592   3724864.0   3724864.0   3724864   3724864    10  ...
23       465592  13194532.0  13194532.0  13194532  13194532    10  ...
24      1243940       128.0       128.0       128       128    10  ...
25      1243940  29215368.0  29215368.0  29215368  29215368    10  ...
26      1243940    622784.0    622784.0    622784    622784    10  ...
27      1243940   1031274.0   1031274.0   1031274   1031274    10  ...
28      1243940   9951648.0   9951648.0   9951648   9951648    10  ...
29      1243940  35256299.0  35256299.0  35256299  35256299    10  ...
30      1586336       128.0       128.0       128       128    10  ...
31      1586336  37243323.0  37243323.0  37243323  37243323    10  ...
32      1586336    622784.0    622784.0    622784    622784    10  ...
33      1586336   1031274.0   1031274.0   1031274   1031274    10  ...
34      1586336  12690816.0  12690816.0  12690816  12690816    10  ...
35      1586336  44966269.0  44966269.0  44966269  44966269    10  ...
36        70296       128.0       128.0       128       128    10  ...
37        70296   1668186.0   1668186.0   1668186   1668186    10  ...
38        70296    562592.0    562592.0    562592    562592    10  ...
39        70296    931581.0    931581.0    931581    931581    10  ...
40        70296    562496.0    562496.0    562496    562496    10  ...
41        70296   1997605.0   1997605.0   1997605   1997605    10  ...
42      2248808       128.0       128.0       128       128    10  ...
43      2248808  53064648.0  53064648.0  53064648  53064648    10  ...
44      2248808    622784.0    622784.0    622784    622784    10  ...
45      2248808   1031274.0   1031274.0   1031274   1031274    10  ...
46      2248808  17990592.0  17990592.0  17990592  17990592    10  ...
47      2248808  64526577.0  64526577.0  64526577  64526577    10  ...
48       751800       128.0       128.0       128       128    10  ...
49       751800  17771013.0  17771013.0  17771013  17771013    10  ...
50       751800    622784.0    622784.0    622784    622784    10  ...
51       751800   1031274.0   1031274.0   1031274   1031274    10  ...
52       751800   6014528.0   6014528.0   6014528   6014528    10  ...
53       751800  21654211.0  21654211.0  21654211  21654211    10  ...

         Time                                   Cost                        \
          min        max count       std        mean      median       min
0   69.430668  88.024322    10  5.507188         0.0         0.0         0
1   24.537284  40.315757    10  5.905834  48555234.0  48555234.0  48555234
2    0.113236   0.164372    10  0.016478    622656.0    622656.0    622656
3    1.086670   1.473635    10  0.153182   1031274.0   1031274.0   1031274
4    4.151819   9.525802    10  1.687004  16544632.0  16544632.0  16544632
5    2.004188   6.584447    10  1.779211  58610340.0  58610340.0  58610340
6   13.505075  16.437185    10  1.026793         0.0         0.0         0
7    3.853203  13.702507    10  3.611687   9469746.0   9469746.0   9469746
8    0.111720   0.174127    10  0.022278    622656.0    622656.0    622656
9    1.054477   1.490201    10  0.180318   1031274.0   1031274.0   1031274
10   0.817815   1.914947    10  0.408816   3228168.0   3228168.0   3228168
11   0.394658   1.255641    10  0.342575  11437647.0  11437647.0  11437647
12   0.841397   1.240557    10  0.114923         0.0         0.0         0
13   0.270655   0.441678    10  0.066550    624078.0    624078.0    624078
14   0.040329   0.064787    10  0.007931    210720.0    210720.0    210720
15   0.349929   0.498419    10  0.048849    349005.0    349005.0    349005
16   0.050033   0.108128    10  0.019852    210632.0    210632.0    210632
17   0.019361   0.067240    10  0.018027    749052.0    749052.0    749052
18  16.093850  19.126961    10  1.009108         0.0         0.0         0
19   4.800853  12.053705    10  2.379966  10934586.0  10934586.0  10934586
20   0.118998   0.167260    10  0.013759    622656.0    622656.0    622656
21   1.094688   1.542973    10  0.179764   1031274.0   1031274.0   1031274
22   0.997049   2.257467    10  0.539548   3724736.0   3724736.0   3724736
23   0.439008   1.430608    10  0.465720  13194532.0  13194532.0  13194532
24  42.571362  50.491962    10  2.719044         0.0         0.0         0
25  13.913212  21.674618    10  2.786130  29215368.0  29215368.0  29215368
26   0.132902   0.173440    10  0.016478    622656.0    622656.0    622656
27   1.087187   1.547113    10  0.146122   1031274.0   1031274.0   1031274
28   2.637422   4.692691    10  0.629755   9951520.0   9951520.0   9951520
29   1.167554   3.047894    10  0.665879  35256299.0  35256299.0  35256299
30  54.849316  71.757481    10  5.398503         0.0         0.0         0
31  18.672860  32.032391    10  4.369532  37243323.0  37243323.0  37243323
32   0.140861   0.186522    10  0.018089    622656.0    622656.0    622656
33   1.071071   1.565112    10  0.155725   1031274.0   1031274.0   1031274
34   3.225348   7.499994    10  1.491703  12690688.0  12690688.0  12690688
35   1.498061   4.294873    10  0.997543  44966269.0  44966269.0  44966269
36   2.039240   2.830060    10  0.243630         0.0         0.0         0
37   0.691113   2.885840    10  0.815822   1668186.0   1668186.0   1668186
38   0.092820   0.157800    10  0.019502    562464.0    562464.0    562464
39   0.928043   1.344832    10  0.163525    931581.0    931581.0    931581
40   0.117583   0.282045    10  0.051114    562368.0    562368.0    562368
41   0.050924   0.104080    10  0.015903   1997605.0   1997605.0   1997605
42  75.872247  95.110759    10  5.609148         0.0         0.0         0
43  27.896361  44.891714    10  6.513035  53064648.0  53064648.0  53064648
44   0.132784   0.185804    10  0.015986    622656.0    622656.0    622656
45   1.133230   1.585622    10  0.170500   1031274.0   1031274.0   1031274
46   4.884601  10.381198    10  1.790216  17990464.0  17990464.0  17990464
47   2.244388   6.767704    10  1.604723  64526577.0  64526577.0  64526577
48  25.224170  30.628189    10  1.713384         0.0         0.0         0
49   8.021804  20.904825    10  4.308146  17771013.0  17771013.0  17771013
50   0.115203   0.178786    10  0.022225    622656.0    622656.0    622656
51   1.132388   1.617926    10  0.189628   1031274.0   1031274.0   1031274
52   1.469344   4.341839    10  0.977428   6014400.0   6014400.0   6014400
53   0.727165   2.332646    10  0.676625  21654211.0  21654211.0  21654211


         max count  std
0          0    10  0.0
1   48555234    10  0.0
2     622656    10  0.0
3    1031274    10  0.0
4   16544632    10  0.0
5   58610340    10  0.0
6          0    10  0.0
7    9469746    10  0.0
8     622656    10  0.0
9    1031274    10  0.0
10   3228168    10  0.0
11  11437647    10  0.0
12         0    10  0.0
13    624078    10  0.0
14    210720    10  0.0
15    349005    10  0.0
16    210632    10  0.0
17    749052    10  0.0
18         0    10  0.0
19  10934586    10  0.0
20    622656    10  0.0
21   1031274    10  0.0
22   3724736    10  0.0
23  13194532    10  0.0
24         0    10  0.0
25  29215368    10  0.0
26    622656    10  0.0
27   1031274    10  0.0
28   9951520    10  0.0
29  35256299    10  0.0
30         0    10  0.0
31  37243323    10  0.0
32    622656    10  0.0
33   1031274    10  0.0
34  12690688    10  0.0
35  44966269    10  0.0
36         0    10  0.0
37   1668186    10  0.0
38    562464    10  0.0
39    931581    10  0.0
40    562368    10  0.0
41   1997605    10  0.0
42         0    10  0.0
43  53064648    10  0.0
44    622656    10  0.0
45   1031274    10  0.0
46  17990464    10  0.0
47  64526577    10  0.0
48         0    10  0.0
49  17771013    10  0.0
50    622656    10  0.0
51   1031274    10  0.0
52   6014400    10  0.0
53  21654211    10  0.0

[54 rows x 23 columns]

In [14]:
df_agg.to_pickle('data/pre_measure_stat.pkl')

In [2]:
df_stat = pd.read_pickle(r"data/pre_measure_stat.pkl")

In [3]:
df_stat

,Filename,Method,Transformation,Type,OriFile_Size,Mean_Size,Median_Size,Min_Size,Max_Size,Std_Size,Mean_Time,Median_Time,Min_Time,Max_Time,Std_Time,Mean_Cost,Median_Cost,Min_Cost,Max_Cost,Std_Cost
0,Anna_Karenina,Repetition Code,Decoding,.txt,2068079,128.0,128.0,128,128,0.0,77.840437,76.774378,69.430668,88.024322,5.507188,0.0,0.0,0,0,0.0
1,Anna_Karenina,Repetition Code,Encoding,.txt,2068079,48555234.0,48555234.0,48555234,48555234,0.0,31.607374,31.248659,24.537284,40.315757,5.905834,48555234.0,48555234.0,48555234,48555234,0.0
2,Anna_Karenina,Simple Code,Decoding,.txt,2068079,622784.0,622784.0,622784,622784,0.0,0.145694,0.148069,0.113236,0.164372,0.016478,622656.0,622656.0,622656,622656,0.0
3,Anna_Karenina,Simple Code,Encoding,.txt,2068079,1031274.0,1031274.0,1031274,1031274,0.0,1.269170,1.247905,1.086670,1.473635,0.153182,1031274.0,1031274.0,1031274,1031274,0.0
4,Anna_Karenina,XOR-Based Code,Decoding,.txt,2068079,16544760.0,16544760.0,16544760,16544760,0.0,6.117736,5.689381,4.151819,9.525802,1.687004,16544632.0,16544632.0,16544632,16544632,0.0
5,Anna_Karenina,XOR-Based Code,Encoding,.txt,2068079,58610340.0,58610340.0,58610340,58610340,0.0,3.285998,2.367637,2.004188,6.584447,1.779211,58610340.0,58610340.0,58610340,58610340,0.0
6,Around_the_World_in_Eighty_Days,Repetition Code,Decoding,.txt,403521,128.0,128.0,128,128,0.0,14.756059,14.647059,13.505075,16.437185,1.026793,0.0,0.0,0,0,0.0
7,Around_the_World_in_Eighty_Days,Repetition Code,Encoding,.txt,403521,9469746.0,9469746.0,9469746,9469746,0.0,7.468344,5.909235,3.853203,13.702507,3.611687,9469746.0,9469746.0,9469746,9469746,0.0
8,Around_the_World_in_Eighty_Days,Simple Code,Decoding,.txt,403521,622784.0,622784.0,622784,622784,0.0,0.145943,0.143256,0.111720,0.174127,0.022278,622656.0,622656.0,622656,622656,0.0
9,Around_the_World_in_Eighty_Days,Simple Code,Encoding,.txt,403521,1031274.0,1031274.0,1031274,1031274,0.0,1.267286,1.245431,1.054477,1.490201,0.180318,1031274.0,1031274.0,1031274,1031274,0.0
10,Around_the_World_in_Eighty_Days,XOR-Based Code,Decoding,.txt,403521,3228296.0,3228296.0,3228296,3228296,0.0,1.473631,1.581491,0.817815,1.914947,0.408816,3228168.0,3228168.0,3228168,3228168,0.0
11,Around_the_World_in_Eighty_Days,XOR-Based Code,Encoding,.txt,403521,11437647.0,11437647.0,11437647,11437647,0.0,0.817749,0.969391,0.394658,1.255641,0.342575,11437647.0,11437647.0,11437647,11437647,0.0
12,La_Jeunesse,Repetition Code,Decoding,.jpg,26329,128.0,128.0,128,128,0.0,0.995391,0.961716,0.841397,1.240557,0.114923,0.0,0.0,0,0,0.0
13,La_Jeunesse,Repetition Code,Encoding,.jpg,26329,624078.0,624078.0,624078,624078,0.0,0.336690,0.315723,0.270655,0.441678,0.066550,624078.0,624078.0,624078,624078,0.0
14,La_Jeunesse,Simple Code,Decoding,.jpg,26329,210848.0,210848.0,210848,210848,0.0,0.051256,0.050518,0.040329,0.064787,0.007931,210720.0,210720.0,210720,210720,0.0
15,La_Jeunesse,Simple Code,Encoding,.jpg,26329,349005.0,349005.0,349005,349005,0.0,0.419565,0.427707,0.349929,0.498419,0.048849,349005.0,349005.0,349005,349005,0.0
16,La_Jeunesse,XOR-Based Code,Decoding,.jpg,26329,210760.0,210760.0,210760,210760,0.0,0.079253,0.084811,0.050033,0.108128,0.019852,210632.0,210632.0,210632,210632,0.0
17,La_Jeunesse,XOR-Based Code,Encoding,.jpg,26329,749052.0,749052.0,749052,749052,0.0,0.041518,0.035054,0.019361,0.067240,0.018027,749052.0,749052.0,749052,749052,0.0
18,The_Picture_of_Dorian_Gray,Repetition Code,Decoding,.txt,465592,128.0,128.0,128,128,0.0,17.400029,17.180545,16.093850,19.126961,1.009108,0.0,0.0,0,0,0.0
19,The_Picture_of_Dorian_Gray,Repetition Code,Encoding,.txt,465592,10934586.0,10934586.0,10934586,10934586,0.0,7.277136,6.900356,4.800853,12.053705,2.379966,10934586.0,10934586.0,10934586,10934586,0.0
20,The_Picture_of_Dorian_Gray,Simple Code,Decoding,.txt,465592,622784.0,622784.0,622784,622784,0.0,0.149017,0.151512,0.118998,0.167260,0.013759,622656.0,622656.0,622656,622656,0.0
21,The_Picture_of_Dorian_Gray,Simple Code,Encoding,.txt,465592,1031274.0,1031274.0,1031274,1031274,0.0,1.256536,1.156910,1.094688,1.542973,0.179764,1031274.0,1031274.0,1031274,1031274,0.0
22,The_Picture_of_Dorian_Gray,XOR-Based Code,Decoding,.txt,465592,3724864.0,3724864.0,3724864,3724864,0.0,1.506828,1.232886,0.997049,2.257467,0.539548,3724736.0,3724736.0,3724736,3724736,0.0
23,The_Picture_of_Dorian_Gray,XOR-Based Code,Encoding,.txt,465592,13194532.0,13194532.0,13194532,13194532,0.0,0.822817,0.473197,0.439008,1.430608,0.465720,13194532.0,13194532.0,13194532,13194532,0.0
24,The_Republic_Plato,Repetition Code,Decoding,.txt,1243940,128.0,128.0,128,128,0.0,46.362251,45.558114,42.571362,50.491962,2.719044,0.0,0.0,0,0,0.0
25,The_Republic_Plato,Repetition Code,Encoding,.txt,1243940,29215368.0,29215368.0,29215368,29215368,0.0,17.039265,16.683977,13.913212,21.674618,2.786130,29215368.0,29215368.0,29215368,29215368,0.0
26,The_Republic_Plato,Simple Code,Decoding,.txt,1243940,622784.0,622784.0,622784,622784,0.0,0.154100,0.153208,0.132902,0.173440,0.016478,622656.0,622656.0,622656,622656,0.0
27,The_Republic_Plato,Simple Code,Encoding,.txt,1243940,1031274.0,1031274.0,1031274,1031274,0.0,1.260271,1.236617,1.087187,1.547113,0.146122,1031274.0,1031274.0,1031274,1031274,0.0
28,The_Republic_Plato,XOR-Based Code,Decoding,.txt,1243940,9951648.0,9951648.0,9951648,9951648,0.0,3.646704,3.482655,2.637422,4.692691,0.629755,9951520.0,9951520.0,9951520,9951520,0.0
29,The_Republic_Plato,XOR-Based Code,Encoding,.txt,1243940,35256299.0,35256299.0,35256299,35256299,0.0,1.624269,1.317596,1.167554,3.047894,0.665879,35256299.0,35256299.0,35256299,35256299,0.0
30,Ulysses,Repetition Code,Decoding,.txt,1586336,128.0,128.0,128,128,0.0,61.595433,63.043663,54.849316,71.757481,5.398503,0.0,0.0,0,0,0.0
31,Ulysses,Repetition Code,Encoding,.txt,1586336,37243323.0,37243323.0,37243323,37243323,0.0,23.091148,21.742941,18.672860,32.032391,4.369532,37243323.0,37243323.0,37243323,37243323,0.0
32,Ulysses,Simple Code,Decoding,.txt,1586336,622784.0,622784.0,622784,622784,0.0,0.160736,0.155265,0.140861,0.186522,0.018089,622656.0,622656.0,622656,622656,0.0
33,Ulysses,Simple Code,Encoding,.txt,1586336,1031274.0,1031274.0,1031274,1031274,0.0,1.288431,1.226764,1.071071,1.565112,0.155725,1031274.0,1031274.0,1031274,1031274,0.0
34,Ulysses,XOR-Based Code,Decoding,.txt,1586336,12690816.0,12690816.0,12690816,12690816,0.0,4.759035,4.487206,3.225348,7.499994,1.491703,12690688.0,12690688.0,12690688,12690688,0.0
35,Ulysses,XOR-Based Code,Encoding,.txt,1586336,44966269.0,44966269.0,44966269,44966269,0.0,2.339750,1.854134,1.498061,4.294873,0.997543,44966269.0,44966269.0,44966269,44966269,0.0
36,Vue_de_la_Buena_Vista,Repetition Code,Decoding,.jpg,70296,128.0,128.0,128,128,0.0,2.435162,2.472652,2.039240,2.830060,0.243630,0.0,0.0,0,0,0.0
37,Vue_de_la_Buena_Vista,Repetition Code,Encoding,.jpg,70296,1668186.0,1668186.0,1668186,1668186,0.0,1.617927,1.543016,0.691113,2.885840,0.815822,1668186.0,1668186.0,1668186,1668186,0.0
38,Vue_de_la_Buena_Vista,Simple Code,Decoding,.jpg,70296,562592.0,562592.0,562592,562592,0.0,0.130026,0.137809,0.092820,0.157800,0.019502,562464.0,562464.0,562464,562464,0.0
39,Vue_de_la_Buena_Vista,Simple Code,Encoding,.jpg,70296,931581.0,931581.0,931581,931581,0.0,1.131019,1.108792,0.928043,1.344832,0.163525,931581.0,931581.0,931581,931581,0.0
40,Vue_de_la_Buena_Vista,XOR-Based Code,Decoding,.jpg,70296,562496.0,562496.0,562496,562496,0.0,0.199052,0.194732,0.117583,0.282045,0.051114,562368.0,562368.0,562368,562368,0.0
41,Vue_de_la_Buena_Vista,XOR-Based Code,Encoding,.jpg,70296,1997605.0,1997605.0,1997605,1997605,0.0,0.072204,0.069056,0.050924,0.104080,0.015903,1997605.0,1997605.0,1997605,1997605,0.0
42,bbc_house,Repetition Code,Decoding,.wav,2248808,128.0,128.0,128,128,0.0,84.954221,83.913800,75.872247,95.110759,5.609148,0.0,0.0,0,0,0.0
43,bbc_house,Repetition Code,Encoding,.wav,2248808,53064648.0,53064648.0,53064648,53064648,0.0,35.077039,32.671307,27.896361,44.891714,6.513035,53064648.0,53064648.0,53064648,53064648,0.0
44,bbc_house,Simple Code,Decoding,.wav,2248808,622784.0,622784.0,622784,622784,0.0,0.154401,0.153800,0.132784,0.185804,0.015986,622656.0,622656.0,622656,622656,0.0
45,bbc_house,Simple Code,Encoding,.wav,2248808,1031274.0,1031274.0,1031274,1031274,0.0,1.323869,1.273211,1.133230,1.585622,0.170500,1031274.0,1031274.0,1031274,1031274,0.0
46,bbc_house,XOR-Based Code,Decoding,.wav,2248808,17990592.0,17990592.0,17990592,17990592,0.0,6.943856,6.537761,4.884601,10.381198,1.790216,17990464.0,17990464.0,17990464,17990464,0.0
47,bbc_house,XOR-Based Code,Encoding,.wav,2248808,64526577.0,64526577.0,64526577,64526577,0.0,3.628981,2.681093,2.244388,6.767704,1.604723,64526577.0,64526577.0,64526577,64526577,0.0
48,bbc_peregrine_falcon,Repetition Code,Decoding,.wav,751800,128.0,128.0,128,128,0.0,28.076092,27.686002,25.224170,30.628189,1.713384,0.0,0.0,0,0,0.0
49,bbc_peregrine_falcon,Repetition Code,Encoding,.wav,751800,17771013.0,17771013.0,17771013,17771013,0.0,12.444221,11.482200,8.021804,20.904825,4.308146,17771013.0,17771013.0,17771013,17771013,0.0
50,bbc_peregrine_falcon,Simple Code,Decoding,.wav,751800,622784.0,622784.0,622784,622784,0.0,0.153826,0.161609,0.115203,0.178786,0.022225,622656.0,622656.0,622656,622656,0.0
51,bbc_peregrine_falcon,Simple Code,Encoding,.wav,751800,1031274.0,1031274.0,1031274,1031274,0.0,1.326413,1.298124,1.132388,1.617926,0.189628,1031274.0,1031274.0,1031274,1031274,0.0
52,bbc_peregrine_falcon,XOR-Based Code,Decoding,.wav,751800,6014528.0,6014528.0,6014528,6014528,0.0,2.303345,1.913427,1.469344,4.341839,0.977428,6014400.0,6014400.0,6014400,6014400,0.0
53,bbc_peregrine_falcon,XOR-Based Code,Encoding,.wav,751800,21654211.0,21654211.0,21654211,21654211,0.0,1.301459,0.934893,0.727165,2.332646,0.676625,21654211.0,21654211.0,21654211,21654211,0.0

In [17]:
Filename = df_stat['Filename']
Method = df_stat['Method']
Transformation = df_stat['Transformation']
Type = df_stat['Type']
OriFile_Size = df_stat['OriFile_Size']
Mean_Size = df_stat['Size']['mean']
Median_Size = df_stat['Size']['median']
Min_Size = df_stat['Size']['min']
Max_Size = df_stat['Size']['max']
Std_Size = df_stat['Size']['std']
Mean_Time = df_stat['Time']['mean']
Median_Time = df_stat['Time']['median']
Min_Time = df_stat['Time']['min']
Max_Time = df_stat['Time']['max']
Std_Time = df_stat['Time']['std']
Mean_Cost = df_stat['Cost']['mean']
Median_Cost = df_stat['Cost']['median']
Min_Cost = df_stat['Cost']['min']
Max_Cost = df_stat['Cost']['max']
Std_Cost = df_stat['Cost']['std']

In [18]:
dict = {'Filename': Filename, 'Method': Method, 'Transformation': Transformation, 
        'Type': Type, 'OriFile_Size' : OriFile_Size, 'Mean_Size': Mean_Size, 'Median_Size': Median_Size, 
        'Min_Size': Min_Size, 'Max_Size': Max_Size, 'Std_Size': Std_Size, 
        'Mean_Time': Mean_Time, 'Median_Time': Median_Time, 'Min_Time': Min_Time, 
        'Max_Time': Max_Time, 'Std_Time': Std_Time, 'Mean_Cost': Mean_Cost, 
        'Median_Cost': Median_Cost, 'Min_Cost': Min_Cost, 'Max_Cost': Max_Cost, 
        'Std_Cost': Std_Cost}

In [19]:
df = pd.DataFrame(dict)

In [20]:
df

,Filename,Method,Transformation,Type,OriFile_Size,Mean_Size,Median_Size,Min_Size,Max_Size,Std_Size,Mean_Time,Median_Time,Min_Time,Max_Time,Std_Time,Mean_Cost,Median_Cost,Min_Cost,Max_Cost,Std_Cost
0,Anna_Karenina,Repetition Code,Decoding,.txt,2068079,128.0,128.0,128,128,0.0,77.840437,76.774378,69.430668,88.024322,5.507188,0.0,0.0,0,0,0.0
1,Anna_Karenina,Repetition Code,Encoding,.txt,2068079,48555234.0,48555234.0,48555234,48555234,0.0,31.607374,31.248659,24.537284,40.315757,5.905834,48555234.0,48555234.0,48555234,48555234,0.0
2,Anna_Karenina,Simple Code,Decoding,.txt,2068079,622784.0,622784.0,622784,622784,0.0,0.145694,0.148069,0.113236,0.164372,0.016478,622656.0,622656.0,622656,622656,0.0
3,Anna_Karenina,Simple Code,Encoding,.txt,2068079,1031274.0,1031274.0,1031274,1031274,0.0,1.269170,1.247905,1.086670,1.473635,0.153182,1031274.0,1031274.0,1031274,1031274,0.0
4,Anna_Karenina,XOR-Based Code,Decoding,.txt,2068079,16544760.0,16544760.0,16544760,16544760,0.0,6.117736,5.689381,4.151819,9.525802,1.687004,16544632.0,16544632.0,16544632,16544632,0.0
5,Anna_Karenina,XOR-Based Code,Encoding,.txt,2068079,58610340.0,58610340.0,58610340,58610340,0.0,3.285998,2.367637,2.004188,6.584447,1.779211,58610340.0,58610340.0,58610340,58610340,0.0
6,Around_the_World_in_Eighty_Days,Repetition Code,Decoding,.txt,403521,128.0,128.0,128,128,0.0,14.756059,14.647059,13.505075,16.437185,1.026793,0.0,0.0,0,0,0.0
7,Around_the_World_in_Eighty_Days,Repetition Code,Encoding,.txt,403521,9469746.0,9469746.0,9469746,9469746,0.0,7.468344,5.909235,3.853203,13.702507,3.611687,9469746.0,9469746.0,9469746,9469746,0.0
8,Around_the_World_in_Eighty_Days,Simple Code,Decoding,.txt,403521,622784.0,622784.0,622784,622784,0.0,0.145943,0.143256,0.111720,0.174127,0.022278,622656.0,622656.0,622656,622656,0.0
9,Around_the_World_in_Eighty_Days,Simple Code,Encoding,.txt,403521,1031274.0,1031274.0,1031274,1031274,0.0,1.267286,1.245431,1.054477,1.490201,0.180318,1031274.0,1031274.0,1031274,1031274,0.0
10,Around_the_World_in_Eighty_Days,XOR-Based Code,Decoding,.txt,403521,3228296.0,3228296.0,3228296,3228296,0.0,1.473631,1.581491,0.817815,1.914947,0.408816,3228168.0,3228168.0,3228168,3228168,0.0
11,Around_the_World_in_Eighty_Days,XOR-Based Code,Encoding,.txt,403521,11437647.0,11437647.0,11437647,11437647,0.0,0.817749,0.969391,0.394658,1.255641,0.342575,11437647.0,11437647.0,11437647,11437647,0.0
12,La_Jeunesse,Repetition Code,Decoding,.jpg,26329,128.0,128.0,128,128,0.0,0.995391,0.961716,0.841397,1.240557,0.114923,0.0,0.0,0,0,0.0
13,La_Jeunesse,Repetition Code,Encoding,.jpg,26329,624078.0,624078.0,624078,624078,0.0,0.336690,0.315723,0.270655,0.441678,0.066550,624078.0,624078.0,624078,624078,0.0
14,La_Jeunesse,Simple Code,Decoding,.jpg,26329,210848.0,210848.0,210848,210848,0.0,0.051256,0.050518,0.040329,0.064787,0.007931,210720.0,210720.0,210720,210720,0.0
15,La_Jeunesse,Simple Code,Encoding,.jpg,26329,349005.0,349005.0,349005,349005,0.0,0.419565,0.427707,0.349929,0.498419,0.048849,349005.0,349005.0,349005,349005,0.0
16,La_Jeunesse,XOR-Based Code,Decoding,.jpg,26329,210760.0,210760.0,210760,210760,0.0,0.079253,0.084811,0.050033,0.108128,0.019852,210632.0,210632.0,210632,210632,0.0
17,La_Jeunesse,XOR-Based Code,Encoding,.jpg,26329,749052.0,749052.0,749052,749052,0.0,0.041518,0.035054,0.019361,0.067240,0.018027,749052.0,749052.0,749052,749052,0.0
18,The_Picture_of_Dorian_Gray,Repetition Code,Decoding,.txt,465592,128.0,128.0,128,128,0.0,17.400029,17.180545,16.093850,19.126961,1.009108,0.0,0.0,0,0,0.0
19,The_Picture_of_Dorian_Gray,Repetition Code,Encoding,.txt,465592,10934586.0,10934586.0,10934586,10934586,0.0,7.277136,6.900356,4.800853,12.053705,2.379966,10934586.0,10934586.0,10934586,10934586,0.0
20,The_Picture_of_Dorian_Gray,Simple Code,Decoding,.txt,465592,622784.0,622784.0,622784,622784,0.0,0.149017,0.151512,0.118998,0.167260,0.013759,622656.0,622656.0,622656,622656,0.0
21,The_Picture_of_Dorian_Gray,Simple Code,Encoding,.txt,465592,1031274.0,1031274.0,1031274,1031274,0.0,1.256536,1.156910,1.094688,1.542973,0.179764,1031274.0,1031274.0,1031274,1031274,0.0
22,The_Picture_of_Dorian_Gray,XOR-Based Code,Decoding,.txt,465592,3724864.0,3724864.0,3724864,3724864,0.0,1.506828,1.232886,0.997049,2.257467,0.539548,3724736.0,3724736.0,3724736,3724736,0.0
23,The_Picture_of_Dorian_Gray,XOR-Based Code,Encoding,.txt,465592,13194532.0,13194532.0,13194532,13194532,0.0,0.822817,0.473197,0.439008,1.430608,0.465720,13194532.0,13194532.0,13194532,13194532,0.0
24,The_Republic_Plato,Repetition Code,Decoding,.txt,1243940,128.0,128.0,128,128,0.0,46.362251,45.558114,42.571362,50.491962,2.719044,0.0,0.0,0,0,0.0
25,The_Republic_Plato,Repetition Code,Encoding,.txt,1243940,29215368.0,29215368.0,29215368,29215368,0.0,17.039265,16.683977,13.913212,21.674618,2.786130,29215368.0,29215368.0,29215368,29215368,0.0
26,The_Republic_Plato,Simple Code,Decoding,.txt,1243940,622784.0,622784.0,622784,622784,0.0,0.154100,0.153208,0.132902,0.173440,0.016478,622656.0,622656.0,622656,622656,0.0
27,The_Republic_Plato,Simple Code,Encoding,.txt,1243940,1031274.0,1031274.0,1031274,1031274,0.0,1.260271,1.236617,1.087187,1.547113,0.146122,1031274.0,1031274.0,1031274,1031274,0.0
28,The_Republic_Plato,XOR-Based Code,Decoding,.txt,1243940,9951648.0,9951648.0,9951648,9951648,0.0,3.646704,3.482655,2.637422,4.692691,0.629755,9951520.0,9951520.0,9951520,9951520,0.0
29,The_Republic_Plato,XOR-Based Code,Encoding,.txt,1243940,35256299.0,35256299.0,35256299,35256299,0.0,1.624269,1.317596,1.167554,3.047894,0.665879,35256299.0,35256299.0,35256299,35256299,0.0
30,Ulysses,Repetition Code,Decoding,.txt,1586336,128.0,128.0,128,128,0.0,61.595433,63.043663,54.849316,71.757481,5.398503,0.0,0.0,0,0,0.0
31,Ulysses,Repetition Code,Encoding,.txt,1586336,37243323.0,37243323.0,37243323,37243323,0.0,23.091148,21.742941,18.672860,32.032391,4.369532,37243323.0,37243323.0,37243323,37243323,0.0
32,Ulysses,Simple Code,Decoding,.txt,1586336,622784.0,622784.0,622784,622784,0.0,0.160736,0.155265,0.140861,0.186522,0.018089,622656.0,622656.0,622656,622656,0.0
33,Ulysses,Simple Code,Encoding,.txt,1586336,1031274.0,1031274.0,1031274,1031274,0.0,1.288431,1.226764,1.071071,1.565112,0.155725,1031274.0,1031274.0,1031274,1031274,0.0
34,Ulysses,XOR-Based Code,Decoding,.txt,1586336,12690816.0,12690816.0,12690816,12690816,0.0,4.759035,4.487206,3.225348,7.499994,1.491703,12690688.0,12690688.0,12690688,12690688,0.0
35,Ulysses,XOR-Based Code,Encoding,.txt,1586336,44966269.0,44966269.0,44966269,44966269,0.0,2.339750,1.854134,1.498061,4.294873,0.997543,44966269.0,44966269.0,44966269,44966269,0.0
36,Vue_de_la_Buena_Vista,Repetition Code,Decoding,.jpg,70296,128.0,128.0,128,128,0.0,2.435162,2.472652,2.039240,2.830060,0.243630,0.0,0.0,0,0,0.0
37,Vue_de_la_Buena_Vista,Repetition Code,Encoding,.jpg,70296,1668186.0,1668186.0,1668186,1668186,0.0,1.617927,1.543016,0.691113,2.885840,0.815822,1668186.0,1668186.0,1668186,1668186,0.0
38,Vue_de_la_Buena_Vista,Simple Code,Decoding,.jpg,70296,562592.0,562592.0,562592,562592,0.0,0.130026,0.137809,0.092820,0.157800,0.019502,562464.0,562464.0,562464,562464,0.0
39,Vue_de_la_Buena_Vista,Simple Code,Encoding,.jpg,70296,931581.0,931581.0,931581,931581,0.0,1.131019,1.108792,0.928043,1.344832,0.163525,931581.0,931581.0,931581,931581,0.0
40,Vue_de_la_Buena_Vista,XOR-Based Code,Decoding,.jpg,70296,562496.0,562496.0,562496,562496,0.0,0.199052,0.194732,0.117583,0.282045,0.051114,562368.0,562368.0,562368,562368,0.0
41,Vue_de_la_Buena_Vista,XOR-Based Code,Encoding,.jpg,70296,1997605.0,1997605.0,1997605,1997605,0.0,0.072204,0.069056,0.050924,0.104080,0.015903,1997605.0,1997605.0,1997605,1997605,0.0
42,bbc_house,Repetition Code,Decoding,.wav,2248808,128.0,128.0,128,128,0.0,84.954221,83.913800,75.872247,95.110759,5.609148,0.0,0.0,0,0,0.0
43,bbc_house,Repetition Code,Encoding,.wav,2248808,53064648.0,53064648.0,53064648,53064648,0.0,35.077039,32.671307,27.896361,44.891714,6.513035,53064648.0,53064648.0,53064648,53064648,0.0
44,bbc_house,Simple Code,Decoding,.wav,2248808,622784.0,622784.0,622784,622784,0.0,0.154401,0.153800,0.132784,0.185804,0.015986,622656.0,622656.0,622656,622656,0.0
45,bbc_house,Simple Code,Encoding,.wav,2248808,1031274.0,1031274.0,1031274,1031274,0.0,1.323869,1.273211,1.133230,1.585622,0.170500,1031274.0,1031274.0,1031274,1031274,0.0
46,bbc_house,XOR-Based Code,Decoding,.wav,2248808,17990592.0,17990592.0,17990592,17990592,0.0,6.943856,6.537761,4.884601,10.381198,1.790216,17990464.0,17990464.0,17990464,17990464,0.0
47,bbc_house,XOR-Based Code,Encoding,.wav,2248808,64526577.0,64526577.0,64526577,64526577,0.0,3.628981,2.681093,2.244388,6.767704,1.604723,64526577.0,64526577.0,64526577,64526577,0.0
48,bbc_peregrine_falcon,Repetition Code,Decoding,.wav,751800,128.0,128.0,128,128,0.0,28.076092,27.686002,25.224170,30.628189,1.713384,0.0,0.0,0,0,0.0
49,bbc_peregrine_falcon,Repetition Code,Encoding,.wav,751800,17771013.0,17771013.0,17771013,17771013,0.0,12.444221,11.482200,8.021804,20.904825,4.308146,17771013.0,17771013.0,17771013,17771013,0.0
50,bbc_peregrine_falcon,Simple Code,Decoding,.wav,751800,622784.0,622784.0,622784,622784,0.0,0.153826,0.161609,0.115203,0.178786,0.022225,622656.0,622656.0,622656,622656,0.0
51,bbc_peregrine_falcon,Simple Code,Encoding,.wav,751800,1031274.0,1031274.0,1031274,1031274,0.0,1.326413,1.298124,1.132388,1.617926,0.189628,1031274.0,1031274.0,1031274,1031274,0.0
52,bbc_peregrine_falcon,XOR-Based Code,Decoding,.wav,751800,6014528.0,6014528.0,6014528,6014528,0.0,2.303345,1.913427,1.469344,4.341839,0.977428,6014400.0,6014400.0,6014400,6014400,0.0
53,bbc_peregrine_falcon,XOR-Based Code,Encoding,.wav,751800,21654211.0,21654211.0,21654211,21654211,0.0,1.301459,0.934893,0.727165,2.332646,0.676625,21654211.0,21654211.0,21654211,21654211,0.0

In [21]:
df.to_pickle('data/pre_measure_stat.pkl')

In [4]:
df = pd.read_pickle(r"data/pre_measure_stat.pkl")

In [5]:
df

,Filename,Method,Transformation,Type,OriFile_Size,Mean_Size,Median_Size,Min_Size,Max_Size,Std_Size,Mean_Time,Median_Time,Min_Time,Max_Time,Std_Time,Mean_Cost,Median_Cost,Min_Cost,Max_Cost,Std_Cost
0,Anna_Karenina,Repetition Code,Decoding,.txt,2068079,128.0,128.0,128,128,0.0,77.840437,76.774378,69.430668,88.024322,5.507188,0.0,0.0,0,0,0.0
1,Anna_Karenina,Repetition Code,Encoding,.txt,2068079,48555234.0,48555234.0,48555234,48555234,0.0,31.607374,31.248659,24.537284,40.315757,5.905834,48555234.0,48555234.0,48555234,48555234,0.0
2,Anna_Karenina,Simple Code,Decoding,.txt,2068079,622784.0,622784.0,622784,622784,0.0,0.145694,0.148069,0.113236,0.164372,0.016478,622656.0,622656.0,622656,622656,0.0
3,Anna_Karenina,Simple Code,Encoding,.txt,2068079,1031274.0,1031274.0,1031274,1031274,0.0,1.269170,1.247905,1.086670,1.473635,0.153182,1031274.0,1031274.0,1031274,1031274,0.0
4,Anna_Karenina,XOR-Based Code,Decoding,.txt,2068079,16544760.0,16544760.0,16544760,16544760,0.0,6.117736,5.689381,4.151819,9.525802,1.687004,16544632.0,16544632.0,16544632,16544632,0.0
5,Anna_Karenina,XOR-Based Code,Encoding,.txt,2068079,58610340.0,58610340.0,58610340,58610340,0.0,3.285998,2.367637,2.004188,6.584447,1.779211,58610340.0,58610340.0,58610340,58610340,0.0
6,Around_the_World_in_Eighty_Days,Repetition Code,Decoding,.txt,403521,128.0,128.0,128,128,0.0,14.756059,14.647059,13.505075,16.437185,1.026793,0.0,0.0,0,0,0.0
7,Around_the_World_in_Eighty_Days,Repetition Code,Encoding,.txt,403521,9469746.0,9469746.0,9469746,9469746,0.0,7.468344,5.909235,3.853203,13.702507,3.611687,9469746.0,9469746.0,9469746,9469746,0.0
8,Around_the_World_in_Eighty_Days,Simple Code,Decoding,.txt,403521,622784.0,622784.0,622784,622784,0.0,0.145943,0.143256,0.111720,0.174127,0.022278,622656.0,622656.0,622656,622656,0.0
9,Around_the_World_in_Eighty_Days,Simple Code,Encoding,.txt,403521,1031274.0,1031274.0,1031274,1031274,0.0,1.267286,1.245431,1.054477,1.490201,0.180318,1031274.0,1031274.0,1031274,1031274,0.0
10,Around_the_World_in_Eighty_Days,XOR-Based Code,Decoding,.txt,403521,3228296.0,3228296.0,3228296,3228296,0.0,1.473631,1.581491,0.817815,1.914947,0.408816,3228168.0,3228168.0,3228168,3228168,0.0
11,Around_the_World_in_Eighty_Days,XOR-Based Code,Encoding,.txt,403521,11437647.0,11437647.0,11437647,11437647,0.0,0.817749,0.969391,0.394658,1.255641,0.342575,11437647.0,11437647.0,11437647,11437647,0.0
12,La_Jeunesse,Repetition Code,Decoding,.jpg,26329,128.0,128.0,128,128,0.0,0.995391,0.961716,0.841397,1.240557,0.114923,0.0,0.0,0,0,0.0
13,La_Jeunesse,Repetition Code,Encoding,.jpg,26329,624078.0,624078.0,624078,624078,0.0,0.336690,0.315723,0.270655,0.441678,0.066550,624078.0,624078.0,624078,624078,0.0
14,La_Jeunesse,Simple Code,Decoding,.jpg,26329,210848.0,210848.0,210848,210848,0.0,0.051256,0.050518,0.040329,0.064787,0.007931,210720.0,210720.0,210720,210720,0.0
15,La_Jeunesse,Simple Code,Encoding,.jpg,26329,349005.0,349005.0,349005,349005,0.0,0.419565,0.427707,0.349929,0.498419,0.048849,349005.0,349005.0,349005,349005,0.0
16,La_Jeunesse,XOR-Based Code,Decoding,.jpg,26329,210760.0,210760.0,210760,210760,0.0,0.079253,0.084811,0.050033,0.108128,0.019852,210632.0,210632.0,210632,210632,0.0
17,La_Jeunesse,XOR-Based Code,Encoding,.jpg,26329,749052.0,749052.0,749052,749052,0.0,0.041518,0.035054,0.019361,0.067240,0.018027,749052.0,749052.0,749052,749052,0.0
18,The_Picture_of_Dorian_Gray,Repetition Code,Decoding,.txt,465592,128.0,128.0,128,128,0.0,17.400029,17.180545,16.093850,19.126961,1.009108,0.0,0.0,0,0,0.0
19,The_Picture_of_Dorian_Gray,Repetition Code,Encoding,.txt,465592,10934586.0,10934586.0,10934586,10934586,0.0,7.277136,6.900356,4.800853,12.053705,2.379966,10934586.0,10934586.0,10934586,10934586,0.0
20,The_Picture_of_Dorian_Gray,Simple Code,Decoding,.txt,465592,622784.0,622784.0,622784,622784,0.0,0.149017,0.151512,0.118998,0.167260,0.013759,622656.0,622656.0,622656,622656,0.0
21,The_Picture_of_Dorian_Gray,Simple Code,Encoding,.txt,465592,1031274.0,1031274.0,1031274,1031274,0.0,1.256536,1.156910,1.094688,1.542973,0.179764,1031274.0,1031274.0,1031274,1031274,0.0
22,The_Picture_of_Dorian_Gray,XOR-Based Code,Decoding,.txt,465592,3724864.0,3724864.0,3724864,3724864,0.0,1.506828,1.232886,0.997049,2.257467,0.539548,3724736.0,3724736.0,3724736,3724736,0.0
23,The_Picture_of_Dorian_Gray,XOR-Based Code,Encoding,.txt,465592,13194532.0,13194532.0,13194532,13194532,0.0,0.822817,0.473197,0.439008,1.430608,0.465720,13194532.0,13194532.0,13194532,13194532,0.0
24,The_Republic_Plato,Repetition Code,Decoding,.txt,1243940,128.0,128.0,128,128,0.0,46.362251,45.558114,42.571362,50.491962,2.719044,0.0,0.0,0,0,0.0
25,The_Republic_Plato,Repetition Code,Encoding,.txt,1243940,29215368.0,29215368.0,29215368,29215368,0.0,17.039265,16.683977,13.913212,21.674618,2.786130,29215368.0,29215368.0,29215368,29215368,0.0
26,The_Republic_Plato,Simple Code,Decoding,.txt,1243940,622784.0,622784.0,622784,622784,0.0,0.154100,0.153208,0.132902,0.173440,0.016478,622656.0,622656.0,622656,622656,0.0
27,The_Republic_Plato,Simple Code,Encoding,.txt,1243940,1031274.0,1031274.0,1031274,1031274,0.0,1.260271,1.236617,1.087187,1.547113,0.146122,1031274.0,1031274.0,1031274,1031274,0.0
28,The_Republic_Plato,XOR-Based Code,Decoding,.txt,1243940,9951648.0,9951648.0,9951648,9951648,0.0,3.646704,3.482655,2.637422,4.692691,0.629755,9951520.0,9951520.0,9951520,9951520,0.0
29,The_Republic_Plato,XOR-Based Code,Encoding,.txt,1243940,35256299.0,35256299.0,35256299,35256299,0.0,1.624269,1.317596,1.167554,3.047894,0.665879,35256299.0,35256299.0,35256299,35256299,0.0
30,Ulysses,Repetition Code,Decoding,.txt,1586336,128.0,128.0,128,128,0.0,61.595433,63.043663,54.849316,71.757481,5.398503,0.0,0.0,0,0,0.0
31,Ulysses,Repetition Code,Encoding,.txt,1586336,37243323.0,37243323.0,37243323,37243323,0.0,23.091148,21.742941,18.672860,32.032391,4.369532,37243323.0,37243323.0,37243323,37243323,0.0
32,Ulysses,Simple Code,Decoding,.txt,1586336,622784.0,622784.0,622784,622784,0.0,0.160736,0.155265,0.140861,0.186522,0.018089,622656.0,622656.0,622656,622656,0.0
33,Ulysses,Simple Code,Encoding,.txt,1586336,1031274.0,1031274.0,1031274,1031274,0.0,1.288431,1.226764,1.071071,1.565112,0.155725,1031274.0,1031274.0,1031274,1031274,0.0
34,Ulysses,XOR-Based Code,Decoding,.txt,1586336,12690816.0,12690816.0,12690816,12690816,0.0,4.759035,4.487206,3.225348,7.499994,1.491703,12690688.0,12690688.0,12690688,12690688,0.0
35,Ulysses,XOR-Based Code,Encoding,.txt,1586336,44966269.0,44966269.0,44966269,44966269,0.0,2.339750,1.854134,1.498061,4.294873,0.997543,44966269.0,44966269.0,44966269,44966269,0.0
36,Vue_de_la_Buena_Vista,Repetition Code,Decoding,.jpg,70296,128.0,128.0,128,128,0.0,2.435162,2.472652,2.039240,2.830060,0.243630,0.0,0.0,0,0,0.0
37,Vue_de_la_Buena_Vista,Repetition Code,Encoding,.jpg,70296,1668186.0,1668186.0,1668186,1668186,0.0,1.617927,1.543016,0.691113,2.885840,0.815822,1668186.0,1668186.0,1668186,1668186,0.0
38,Vue_de_la_Buena_Vista,Simple Code,Decoding,.jpg,70296,562592.0,562592.0,562592,562592,0.0,0.130026,0.137809,0.092820,0.157800,0.019502,562464.0,562464.0,562464,562464,0.0
39,Vue_de_la_Buena_Vista,Simple Code,Encoding,.jpg,70296,931581.0,931581.0,931581,931581,0.0,1.131019,1.108792,0.928043,1.344832,0.163525,931581.0,931581.0,931581,931581,0.0
40,Vue_de_la_Buena_Vista,XOR-Based Code,Decoding,.jpg,70296,562496.0,562496.0,562496,562496,0.0,0.199052,0.194732,0.117583,0.282045,0.051114,562368.0,562368.0,562368,562368,0.0
41,Vue_de_la_Buena_Vista,XOR-Based Code,Encoding,.jpg,70296,1997605.0,1997605.0,1997605,1997605,0.0,0.072204,0.069056,0.050924,0.104080,0.015903,1997605.0,1997605.0,1997605,1997605,0.0
42,bbc_house,Repetition Code,Decoding,.wav,2248808,128.0,128.0,128,128,0.0,84.954221,83.913800,75.872247,95.110759,5.609148,0.0,0.0,0,0,0.0
43,bbc_house,Repetition Code,Encoding,.wav,2248808,53064648.0,53064648.0,53064648,53064648,0.0,35.077039,32.671307,27.896361,44.891714,6.513035,53064648.0,53064648.0,53064648,53064648,0.0
44,bbc_house,Simple Code,Decoding,.wav,2248808,622784.0,622784.0,622784,622784,0.0,0.154401,0.153800,0.132784,0.185804,0.015986,622656.0,622656.0,622656,622656,0.0
45,bbc_house,Simple Code,Encoding,.wav,2248808,1031274.0,1031274.0,1031274,1031274,0.0,1.323869,1.273211,1.133230,1.585622,0.170500,1031274.0,1031274.0,1031274,1031274,0.0
46,bbc_house,XOR-Based Code,Decoding,.wav,2248808,17990592.0,17990592.0,17990592,17990592,0.0,6.943856,6.537761,4.884601,10.381198,1.790216,17990464.0,17990464.0,17990464,17990464,0.0
47,bbc_house,XOR-Based Code,Encoding,.wav,2248808,64526577.0,64526577.0,64526577,64526577,0.0,3.628981,2.681093,2.244388,6.767704,1.604723,64526577.0,64526577.0,64526577,64526577,0.0
48,bbc_peregrine_falcon,Repetition Code,Decoding,.wav,751800,128.0,128.0,128,128,0.0,28.076092,27.686002,25.224170,30.628189,1.713384,0.0,0.0,0,0,0.0
49,bbc_peregrine_falcon,Repetition Code,Encoding,.wav,751800,17771013.0,17771013.0,17771013,17771013,0.0,12.444221,11.482200,8.021804,20.904825,4.308146,17771013.0,17771013.0,17771013,17771013,0.0
50,bbc_peregrine_falcon,Simple Code,Decoding,.wav,751800,622784.0,622784.0,622784,622784,0.0,0.153826,0.161609,0.115203,0.178786,0.022225,622656.0,622656.0,622656,622656,0.0
51,bbc_peregrine_falcon,Simple Code,Encoding,.wav,751800,1031274.0,1031274.0,1031274,1031274,0.0,1.326413,1.298124,1.132388,1.617926,0.189628,1031274.0,1031274.0,1031274,1031274,0.0
52,bbc_peregrine_falcon,XOR-Based Code,Decoding,.wav,751800,6014528.0,6014528.0,6014528,6014528,0.0,2.303345,1.913427,1.469344,4.341839,0.977428,6014400.0,6014400.0,6014400,6014400,0.0
53,bbc_peregrine_falcon,XOR-Based Code,Encoding,.wav,751800,21654211.0,21654211.0,21654211,21654211,0.0,1.301459,0.934893,0.727165,2.332646,0.676625,21654211.0,21654211.0,21654211,21654211,0.0

In [6]:
Filename = []
for name in df['Filename']:
    if name not in Filename:
        Filename.append(name)
Filename

['Anna_Karenina',
 'Around_the_World_in_Eighty_Days',
 'La_Jeunesse',
 'The_Picture_of_Dorian_Gray',
 'The_Republic_Plato',
 'Ulysses',
 'Vue_de_la_Buena_Vista',
 'bbc_house',
 'bbc_peregrine_falcon']

In [7]:
df_agg = df.groupby(['Filename', 'Method', 'Type', 'OriFile_Size']).agg({'Mean_Size': ['sum'],'Mean_Time': ['sum'],'Mean_Cost': ['sum']}).reset_index()

In [8]:
df_agg

,Filename,Method,Type,OriFile_Size,Mean_Size,Mean_Time,Mean_Cost
,,,,,sum,sum,sum
0,Anna_Karenina,Repetition Code,.txt,2068079,48555362.0,109.447811,48555234.0
1,Anna_Karenina,Simple Code,.txt,2068079,1654058.0,1.414864,1653930.0
2,Anna_Karenina,XOR-Based Code,.txt,2068079,75155100.0,9.403734,75154972.0
3,Around_the_World_in_Eighty_Days,Repetition Code,.txt,403521,9469874.0,22.224403,9469746.0
4,Around_the_World_in_Eighty_Days,Simple Code,.txt,403521,1654058.0,1.413229,1653930.0
5,Around_the_World_in_Eighty_Days,XOR-Based Code,.txt,403521,14665943.0,2.291381,14665815.0
6,La_Jeunesse,Repetition Code,.jpg,26329,624206.0,1.332081,624078.0
7,La_Jeunesse,Simple Code,.jpg,26329,559853.0,0.470821,559725.0
8,La_Jeunesse,XOR-Based Code,.jpg,26329,959812.0,0.120771,959684.0
9,The_Picture_of_Dorian_Gray,Repetition Code,.txt,465592,10934714.0,24.677164,10934586.0
10,The_Picture_of_Dorian_Gray,Simple Code,.txt,465592,1654058.0,1.405553,1653930.0
11,The_Picture_of_Dorian_Gray,XOR-Based Code,.txt,465592,16919396.0,2.329645,16919268.0
12,The_Republic_Plato,Repetition Code,.txt,1243940,29215496.0,63.401515,29215368.0
13,The_Republic_Plato,Simple Code,.txt,1243940,1654058.0,1.414372,1653930.0
14,The_Republic_Plato,XOR-Based Code,.txt,1243940,45207947.0,5.270973,45207819.0
15,Ulysses,Repetition Code,.txt,1586336,37243451.0,84.686581,37243323.0
16,Ulysses,Simple Code,.txt,1586336,1654058.0,1.449167,1653930.0
17,Ulysses,XOR-Based Code,.txt,1586336,57657085.0,7.098785,57656957.0
18,Vue_de_la_Buena_Vista,Repetition Code,.jpg,70296,1668314.0,4.053090,1668186.0
19,Vue_de_la_Buena_Vista,Simple Code,.jpg,70296,1494173.0,1.261045,1494045.0
20,Vue_de_la_Buena_Vista,XOR-Based Code,.jpg,70296,2560101.0,0.271256,2559973.0
21,bbc_house,Repetition Code,.wav,2248808,53064776.0,120.031259,53064648.0
22,bbc_house,Simple Code,.wav,2248808,1654058.0,1.478270,1653930.0
23,bbc_house,XOR-Based Code,.wav,2248808,82517169.0,10.572836,82517041.0
24,bbc_peregrine_falcon,Repetition Code,.wav,751800,17771141.0,40.520312,17771013.0
25,bbc_peregrine_falcon,Simple Code,.wav,751800,1654058.0,1.480239,1653930.0
26,bbc_peregrine_falcon,XOR-Based Code,.wav,751800,27668739.0,3.604804,27668611.0

In [9]:
Filename = df_agg['Filename']
Method = df_agg['Method']
Type = df_agg['Type']
OriFile_Size = df_agg['OriFile_Size']
Sum_Mean_Size = df_agg['Mean_Size']['sum']
Sum_Mean_Time = df_agg['Mean_Time']['sum']
Sum_Mean_Cost = df_agg['Mean_Cost']['sum']

In [10]:
dict = {'Filename': Filename, 'Method': Method, 
        'Type': Type, 'OriFile_Size' : OriFile_Size, 'Sum_Mean_Size': Sum_Mean_Size, 
        'Sum_Mean_Time': Sum_Mean_Time,
        'Sum_Mean_Cost': Sum_Mean_Cost}

In [11]:
df_agg_summary = pd.DataFrame(dict)

In [12]:
df_agg_summary

,Filename,Method,Type,OriFile_Size,Sum_Mean_Size,Sum_Mean_Time,Sum_Mean_Cost
0,Anna_Karenina,Repetition Code,.txt,2068079,48555362.0,109.447811,48555234.0
1,Anna_Karenina,Simple Code,.txt,2068079,1654058.0,1.414864,1653930.0
2,Anna_Karenina,XOR-Based Code,.txt,2068079,75155100.0,9.403734,75154972.0
3,Around_the_World_in_Eighty_Days,Repetition Code,.txt,403521,9469874.0,22.224403,9469746.0
4,Around_the_World_in_Eighty_Days,Simple Code,.txt,403521,1654058.0,1.413229,1653930.0
5,Around_the_World_in_Eighty_Days,XOR-Based Code,.txt,403521,14665943.0,2.291381,14665815.0
6,La_Jeunesse,Repetition Code,.jpg,26329,624206.0,1.332081,624078.0
7,La_Jeunesse,Simple Code,.jpg,26329,559853.0,0.470821,559725.0
8,La_Jeunesse,XOR-Based Code,.jpg,26329,959812.0,0.120771,959684.0
9,The_Picture_of_Dorian_Gray,Repetition Code,.txt,465592,10934714.0,24.677164,10934586.0
10,The_Picture_of_Dorian_Gray,Simple Code,.txt,465592,1654058.0,1.405553,1653930.0
11,The_Picture_of_Dorian_Gray,XOR-Based Code,.txt,465592,16919396.0,2.329645,16919268.0
12,The_Republic_Plato,Repetition Code,.txt,1243940,29215496.0,63.401515,29215368.0
13,The_Republic_Plato,Simple Code,.txt,1243940,1654058.0,1.414372,1653930.0
14,The_Republic_Plato,XOR-Based Code,.txt,1243940,45207947.0,5.270973,45207819.0
15,Ulysses,Repetition Code,.txt,1586336,37243451.0,84.686581,37243323.0
16,Ulysses,Simple Code,.txt,1586336,1654058.0,1.449167,1653930.0
17,Ulysses,XOR-Based Code,.txt,1586336,57657085.0,7.098785,57656957.0
18,Vue_de_la_Buena_Vista,Repetition Code,.jpg,70296,1668314.0,4.053090,1668186.0
19,Vue_de_la_Buena_Vista,Simple Code,.jpg,70296,1494173.0,1.261045,1494045.0
20,Vue_de_la_Buena_Vista,XOR-Based Code,.jpg,70296,2560101.0,0.271256,2559973.0
21,bbc_house,Repetition Code,.wav,2248808,53064776.0,120.031259,53064648.0
22,bbc_house,Simple Code,.wav,2248808,1654058.0,1.478270,1653930.0
23,bbc_house,XOR-Based Code,.wav,2248808,82517169.0,10.572836,82517041.0
24,bbc_peregrine_falcon,Repetition Code,.wav,751800,17771141.0,40.520312,17771013.0
25,bbc_peregrine_falcon,Simple Code,.wav,751800,1654058.0,1.480239,1653930.0
26,bbc_peregrine_falcon,XOR-Based Code,.wav,751800,27668739.0,3.604804,27668611.0

In [15]:
path_original_data = os.path.join('..', 'Data', 'Original')
path_encoded_dna = os.path.join('..', 'Data', 'Encoded_DNA')
path_decoded_dna = os.path.join('..', 'Data', 'Decoded_DNA')

encoding_method = ["Repetition Code", "Simple Code",  "XOR-Based Code"]

df_result = pd.DataFrame(columns=['Filename', 'Method', 'Type', 'Similarity'])

for list_file in os.listdir(path_original_data):
    string_file_no_extension = os.path.splitext(list_file)[0]
    file_extension = os.path.splitext(list_file)[1]
    before_encoding = string_file_no_extension+'.npy'
    bit_path = os.path.join(path_encoded_dna, before_encoding)
    original_bit = np.load(bit_path)
    for em in encoding_method:
        if em == 'Simple Code':
            file_name = string_file_no_extension + '_simple.npy'
        elif em == 'Repetition Code':
            file_name = string_file_no_extension + '_repetition.npy'
        elif em == 'The 2D Code':
            file_name = string_file_no_extension + '_2d.npy'
        elif em == 'XOR-Based Code':
            file_name = string_file_no_extension + '_xor.npy'
        path_decoded = os.path.join(path_decoded_dna, file_name)
        bit_decoded = np.load(path_decoded)

        if len(bit_decoded) == len(original_bit):
            i = 0
            status = 'Same'
            while i < len(bit_decoded) and status == 'Same':
                if bit_decoded[i] == original_bit[i]:
                    status = 'Same'
                else:
                    status = 'Different'
                i += 1
        else:
            status = 'Different'

        list = [string_file_no_extension, em, file_extension, status]
        df_result.loc[len(df_result)] = list

In [16]:
df_result

                           Filename           Method  Type Similarity
0                     Anna_Karenina  Repetition Code  .txt  Different
1                     Anna_Karenina      Simple Code  .txt  Different
2                     Anna_Karenina   XOR-Based Code  .txt       Same
3   Around_the_World_in_Eighty_Days  Repetition Code  .txt  Different
4   Around_the_World_in_Eighty_Days      Simple Code  .txt  Different
5   Around_the_World_in_Eighty_Days   XOR-Based Code  .txt       Same
6                         bbc_house  Repetition Code  .wav  Different
7                         bbc_house      Simple Code  .wav  Different
8                         bbc_house   XOR-Based Code  .wav       Same
9              bbc_peregrine_falcon  Repetition Code  .wav  Different
10             bbc_peregrine_falcon      Simple Code  .wav  Different
11             bbc_peregrine_falcon   XOR-Based Code  .wav       Same
12                      La_Jeunesse  Repetition Code  .jpg  Different
13                      La_Jeunesse      Simple Code  .jpg  Different
14                      La_Jeunesse   XOR-Based Code  .jpg       Same
15       The_Picture_of_Dorian_Gray  Repetition Code  .txt  Different
16       The_Picture_of_Dorian_Gray      Simple Code  .txt  Different
17       The_Picture_of_Dorian_Gray   XOR-Based Code  .txt       Same
18               The_Republic_Plato  Repetition Code  .txt  Different
19               The_Republic_Plato      Simple Code  .txt  Different
20               The_Republic_Plato   XOR-Based Code  .txt       Same
21                          Ulysses  Repetition Code  .txt  Different
22                          Ulysses      Simple Code  .txt  Different
23                          Ulysses   XOR-Based Code  .txt       Same
24            Vue_de_la_Buena_Vista  Repetition Code  .jpg  Different
25            Vue_de_la_Buena_Vista      Simple Code  .jpg  Different
26            Vue_de_la_Buena_Vista   XOR-Based Code  .jpg       Same

In [19]:
result = pd.concat([df_agg_summary, df_result['Similarity']], axis=1, join="inner")

In [20]:
result

,Filename,Method,Type,OriFile_Size,Sum_Mean_Size,Sum_Mean_Time,Sum_Mean_Cost,Similarity
0,Anna_Karenina,Repetition Code,.txt,2068079,48555362.0,109.447811,48555234.0,Different
1,Anna_Karenina,Simple Code,.txt,2068079,1654058.0,1.414864,1653930.0,Different
2,Anna_Karenina,XOR-Based Code,.txt,2068079,75155100.0,9.403734,75154972.0,Same
3,Around_the_World_in_Eighty_Days,Repetition Code,.txt,403521,9469874.0,22.224403,9469746.0,Different
4,Around_the_World_in_Eighty_Days,Simple Code,.txt,403521,1654058.0,1.413229,1653930.0,Different
5,Around_the_World_in_Eighty_Days,XOR-Based Code,.txt,403521,14665943.0,2.291381,14665815.0,Same
6,La_Jeunesse,Repetition Code,.jpg,26329,624206.0,1.332081,624078.0,Different
7,La_Jeunesse,Simple Code,.jpg,26329,559853.0,0.470821,559725.0,Different
8,La_Jeunesse,XOR-Based Code,.jpg,26329,959812.0,0.120771,959684.0,Same
9,The_Picture_of_Dorian_Gray,Repetition Code,.txt,465592,10934714.0,24.677164,10934586.0,Different
10,The_Picture_of_Dorian_Gray,Simple Code,.txt,465592,1654058.0,1.405553,1653930.0,Different
11,The_Picture_of_Dorian_Gray,XOR-Based Code,.txt,465592,16919396.0,2.329645,16919268.0,Same
12,The_Republic_Plato,Repetition Code,.txt,1243940,29215496.0,63.401515,29215368.0,Different
13,The_Republic_Plato,Simple Code,.txt,1243940,1654058.0,1.414372,1653930.0,Different
14,The_Republic_Plato,XOR-Based Code,.txt,1243940,45207947.0,5.270973,45207819.0,Same
15,Ulysses,Repetition Code,.txt,1586336,37243451.0,84.686581,37243323.0,Different
16,Ulysses,Simple Code,.txt,1586336,1654058.0,1.449167,1653930.0,Different
17,Ulysses,XOR-Based Code,.txt,1586336,57657085.0,7.098785,57656957.0,Same
18,Vue_de_la_Buena_Vista,Repetition Code,.jpg,70296,1668314.0,4.053090,1668186.0,Different
19,Vue_de_la_Buena_Vista,Simple Code,.jpg,70296,1494173.0,1.261045,1494045.0,Different
20,Vue_de_la_Buena_Vista,XOR-Based Code,.jpg,70296,2560101.0,0.271256,2559973.0,Same
21,bbc_house,Repetition Code,.wav,2248808,53064776.0,120.031259,53064648.0,Different
22,bbc_house,Simple Code,.wav,2248808,1654058.0,1.478270,1653930.0,Different
23,bbc_house,XOR-Based Code,.wav,2248808,82517169.0,10.572836,82517041.0,Same
24,bbc_peregrine_falcon,Repetition Code,.wav,751800,17771141.0,40.520312,17771013.0,Different
25,bbc_peregrine_falcon,Simple Code,.wav,751800,1654058.0,1.480239,1653930.0,Different
26,bbc_peregrine_falcon,XOR-Based Code,.wav,751800,27668739.0,3.604804,27668611.0,Same

In [21]:
result.to_pickle('data/pre_measure_stat_sum.pkl')