In [1]:
import pandas as pd
import os

In [2]:
import pkg_resources
import types
def get_imports():
    for name, val in globals().items():
        if isinstance(val, types.ModuleType):
            # Split ensures you get root package, 
            # not just imported function
            name = val.__name__.split(".")[0]

        elif isinstance(val, type):
            name = val.__module__.split(".")[0]

        # Some packages are weird and have different
        # imported names vs. system/pip names. Unfortunately,
        # there is no systematic way to get pip names from
        # a package's imported name. You'll have to add
        # exceptions to this list manually!
        poorly_named_packages = {
            "PIL": "Pillow",
            "sklearn": "scikit-learn"
        }
        if name in poorly_named_packages.keys():
            name = poorly_named_packages[name]

        yield name
imports = list(set(get_imports()))

# The only way I found to get the version of the root package
# from only the name of the package is to cross-check the names 
# of installed packages vs. imported packages
requirements = []
for m in pkg_resources.working_set:
    if m.project_name in imports and m.project_name!="pip":
        requirements.append((m.project_name, m.version))

for r in requirements:
    print("{}=={}".format(*r))

pandas==1.5.1

In [21]:
path_original_data = r'C:\Users\heldi\Downloads\Coding\Projects\DNA_Encodings\Data\Original'
size_df = pd.DataFrame(columns=['Filename', 'Size'])
for file_name in os.listdir(path_original_data):
    path = os.path.join(path_decoded_dna, file_name)
    size = os.path.getsize(path)
    file_name1 = os.path.splitext(file_name)[0]
    list = [file_name1, size]
    size_df.loc[len(size_df)] = list
size_df

                          Filename     Size
0                    Anna_Karenina  2068079
1  Around_the_World_in_Eighty_Days   403521
2                        bbc_house  2248808
3             bbc_peregrine_falcon   751800
4                      La_Jeunesse    26329
5       The_Picture_of_Dorian_Gray   465592
6               The_Republic_Plato  1243940
7                          Ulysses  1586336
8            Vue_de_la_Buena_Vista    70296

In [14]:
df_measure = pd.read_pickle(r"data/pre_measure.pkl")

In [22]:
df_measure

,Filename,Method,Transformation,Size,Cost,Time,Type
0,Anna_Karenina,Repetition Code,Encoding,48555234,48555234,24.537284,.txt
1,Anna_Karenina,Repetition Code,Decoding,128,0,69.430668,.txt
2,Anna_Karenina,Simple Code,Encoding,1031274,1031274,1.087373,.txt
3,Anna_Karenina,Simple Code,Decoding,622784,622656,0.113236,.txt
4,Anna_Karenina,XOR-Based Code,Encoding,58610340,58610340,2.004188,.txt
...,...,...,...,...,...,...,...
535,Vue_de_la_Buena_Vista,Repetition Code,Decoding,128,0,2.335622,.jpg
536,Vue_de_la_Buena_Vista,Simple Code,Encoding,931581,931581,1.268053,.jpg
537,Vue_de_la_Buena_Vista,Simple Code,Decoding,562592,562464,0.148494,.jpg
538,Vue_de_la_Buena_Vista,XOR-Based Code,Encoding,1997605,1997605,0.068561,.jpg
539,Vue_de_la_Buena_Vista,XOR-Based Code,Decoding,562496,562368,0.230991,.jpg

In [35]:
list = []
for filename in df_measure['Filename']:
    index = size_df.index[size_df['Filename'] == filename]
    size = size_df['Size'].iloc[index].values[0]
    list.append(size)
list

[2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 2068079,
 403521,
 403521,
 403521,
 403521,
 403521,
 403521,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 2248808,
 751800,
 751800,
 751800,
 751800,
 751800,
 751800,
 26329,
 26329,
 26329,
 26329,
 26329,
 26329,
 465592,
 465592,
 465592,
 465592,
 465592,
 465592,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1243940,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 1586336,
 70296,
 70296,
 70296,
 70296,
 70296,
 70296]

In [36]:
df_measure['OriFile_Size']=list

In [37]:
df_measure

,Filename,Method,Transformation,Size,Cost,Time,Type,OriFile_Size
0,Anna_Karenina,Repetition Code,Encoding,48555234,48555234,24.537284,.txt,2068079
1,Anna_Karenina,Repetition Code,Decoding,128,0,69.430668,.txt,2068079
2,Anna_Karenina,Simple Code,Encoding,1031274,1031274,1.087373,.txt,2068079
3,Anna_Karenina,Simple Code,Decoding,622784,622656,0.113236,.txt,2068079
4,Anna_Karenina,XOR-Based Code,Encoding,58610340,58610340,2.004188,.txt,2068079
...,...,...,...,...,...,...,...,...
535,Vue_de_la_Buena_Vista,Repetition Code,Decoding,128,0,2.335622,.jpg,70296
536,Vue_de_la_Buena_Vista,Simple Code,Encoding,931581,931581,1.268053,.jpg,70296
537,Vue_de_la_Buena_Vista,Simple Code,Decoding,562592,562464,0.148494,.jpg,70296
538,Vue_de_la_Buena_Vista,XOR-Based Code,Encoding,1997605,1997605,0.068561,.jpg,70296
539,Vue_de_la_Buena_Vista,XOR-Based Code,Decoding,562496,562368,0.230991,.jpg,70296

In [38]:
df_measure.to_pickle('data/pre_measure.pkl')

In [18]:
df_agg = df_measure.groupby(['Filename', 'Method', 'Transformation', 'Type']).agg({'Size': ['mean', 'median', 'min', 'max', 'count', 'std'],'Time': ['mean', 'median', 'min', 'max', 'count', 'std'],'Cost': ['mean', 'median', 'min', 'max', 'count', 'std']}).reset_index()

In [16]:
df_agg

                           Filename           Method Transformation  Type  \

0                     Anna_Karenina  Repetition Code       Decoding  .txt
1                     Anna_Karenina  Repetition Code       Encoding  .txt
2                     Anna_Karenina      Simple Code       Decoding  .txt
3                     Anna_Karenina      Simple Code       Encoding  .txt
4                     Anna_Karenina   XOR-Based Code       Decoding  .txt
5                     Anna_Karenina   XOR-Based Code       Encoding  .txt
6   Around_the_World_in_Eighty_Days  Repetition Code       Decoding  .txt
7   Around_the_World_in_Eighty_Days  Repetition Code       Encoding  .txt
8   Around_the_World_in_Eighty_Days      Simple Code       Decoding  .txt
9   Around_the_World_in_Eighty_Days      Simple Code       Encoding  .txt
10  Around_the_World_in_Eighty_Days   XOR-Based Code       Decoding  .txt
11  Around_the_World_in_Eighty_Days   XOR-Based Code       Encoding  .txt
12                      La_Jeunesse  Repetition Code       Decoding  .jpg
13                      La_Jeunesse  Repetition Code       Encoding  .jpg
14                      La_Jeunesse      Simple Code       Decoding  .jpg
15                      La_Jeunesse      Simple Code       Encoding  .jpg
16                      La_Jeunesse   XOR-Based Code       Decoding  .jpg
17                      La_Jeunesse   XOR-Based Code       Encoding  .jpg
18       The_Picture_of_Dorian_Gray  Repetition Code       Decoding  .txt
19       The_Picture_of_Dorian_Gray  Repetition Code       Encoding  .txt
20       The_Picture_of_Dorian_Gray      Simple Code       Decoding  .txt
21       The_Picture_of_Dorian_Gray      Simple Code       Encoding  .txt
22       The_Picture_of_Dorian_Gray   XOR-Based Code       Decoding  .txt
23       The_Picture_of_Dorian_Gray   XOR-Based Code       Encoding  .txt
24               The_Republic_Plato  Repetition Code       Decoding  .txt
25               The_Republic_Plato  Repetition Code       Encoding  .txt
26               The_Republic_Plato      Simple Code       Decoding  .txt
27               The_Republic_Plato      Simple Code       Encoding  .txt
28               The_Republic_Plato   XOR-Based Code       Decoding  .txt
29               The_Republic_Plato   XOR-Based Code       Encoding  .txt
30                          Ulysses  Repetition Code       Decoding  .txt
31                          Ulysses  Repetition Code       Encoding  .txt
32                          Ulysses      Simple Code       Decoding  .txt
33                          Ulysses      Simple Code       Encoding  .txt
34                          Ulysses   XOR-Based Code       Decoding  .txt
35                          Ulysses   XOR-Based Code       Encoding  .txt
36            Vue_de_la_Buena_Vista  Repetition Code       Decoding  .jpg
37            Vue_de_la_Buena_Vista  Repetition Code       Encoding  .jpg
38            Vue_de_la_Buena_Vista      Simple Code       Decoding  .jpg
39            Vue_de_la_Buena_Vista      Simple Code       Encoding  .jpg
40            Vue_de_la_Buena_Vista   XOR-Based Code       Decoding  .jpg
41            Vue_de_la_Buena_Vista   XOR-Based Code       Encoding  .jpg
42                        bbc_house  Repetition Code       Decoding  .wav
43                        bbc_house  Repetition Code       Encoding  .wav
44                        bbc_house      Simple Code       Decoding  .wav
45                        bbc_house      Simple Code       Encoding  .wav
46                        bbc_house   XOR-Based Code       Decoding  .wav
47                        bbc_house   XOR-Based Code       Encoding  .wav
48             bbc_peregrine_falcon  Repetition Code       Decoding  .wav
49             bbc_peregrine_falcon  Repetition Code       Encoding  .wav
50             bbc_peregrine_falcon      Simple Code       Decoding  .wav
51             bbc_peregrine_falcon      Simple Code       Encoding  .wav
52             bbc_peregrine_falcon   XOR-Based Code       Decoding  .wav
53             bbc_peregrine_falcon   XOR-Based Code       Encoding  .wav

          Size                                             ...       Time  \
          mean      median       min       max count  std  ...        min
0        128.0       128.0       128       128    10  0.0  ...  69.430668
1   48555234.0  48555234.0  48555234  48555234    10  0.0  ...  24.537284
2     622784.0    622784.0    622784    622784    10  0.0  ...   0.113236
3    1031274.0   1031274.0   1031274   1031274    10  0.0  ...   1.086670
4   16544760.0  16544760.0  16544760  16544760    10  0.0  ...   4.151819
5   58610340.0  58610340.0  58610340  58610340    10  0.0  ...   2.004188
6        128.0       128.0       128       128    10  0.0  ...  13.505075
7    9469746.0   9469746.0   9469746   9469746    10  0.0  ...   3.853203
8     622784.0    622784.0    622784    622784    10  0.0  ...   0.111720
9    1031274.0   1031274.0   1031274   1031274    10  0.0  ...   1.054477
10   3228296.0   3228296.0   3228296   3228296    10  0.0  ...   0.817815
11  11437647.0  11437647.0  11437647  11437647    10  0.0  ...   0.394658
12       128.0       128.0       128       128    10  0.0  ...   0.841397
13    624078.0    624078.0    624078    624078    10  0.0  ...   0.270655
14    210848.0    210848.0    210848    210848    10  0.0  ...   0.040329
15    349005.0    349005.0    349005    349005    10  0.0  ...   0.349929
16    210760.0    210760.0    210760    210760    10  0.0  ...   0.050033
17    749052.0    749052.0    749052    749052    10  0.0  ...   0.019361
18       128.0       128.0       128       128    10  0.0  ...  16.093850
19  10934586.0  10934586.0  10934586  10934586    10  0.0  ...   4.800853
20    622784.0    622784.0    622784    622784    10  0.0  ...   0.118998
21   1031274.0   1031274.0   1031274   1031274    10  0.0  ...   1.094688
22   3724864.0   3724864.0   3724864   3724864    10  0.0  ...   0.997049
23  13194532.0  13194532.0  13194532  13194532    10  0.0  ...   0.439008
24       128.0       128.0       128       128    10  0.0  ...  42.571362
25  29215368.0  29215368.0  29215368  29215368    10  0.0  ...  13.913212
26    622784.0    622784.0    622784    622784    10  0.0  ...   0.132902
27   1031274.0   1031274.0   1031274   1031274    10  0.0  ...   1.087187
28   9951648.0   9951648.0   9951648   9951648    10  0.0  ...   2.637422
29  35256299.0  35256299.0  35256299  35256299    10  0.0  ...   1.167554
30       128.0       128.0       128       128    10  0.0  ...  54.849316
31  37243323.0  37243323.0  37243323  37243323    10  0.0  ...  18.672860
32    622784.0    622784.0    622784    622784    10  0.0  ...   0.140861
33   1031274.0   1031274.0   1031274   1031274    10  0.0  ...   1.071071
34  12690816.0  12690816.0  12690816  12690816    10  0.0  ...   3.225348
35  44966269.0  44966269.0  44966269  44966269    10  0.0  ...   1.498061
36       128.0       128.0       128       128    10  0.0  ...   2.039240
37   1668186.0   1668186.0   1668186   1668186    10  0.0  ...   0.691113
38    562592.0    562592.0    562592    562592    10  0.0  ...   0.092820
39    931581.0    931581.0    931581    931581    10  0.0  ...   0.928043
40    562496.0    562496.0    562496    562496    10  0.0  ...   0.117583
41   1997605.0   1997605.0   1997605   1997605    10  0.0  ...   0.050924
42       128.0       128.0       128       128    10  0.0  ...  75.872247
43  53064648.0  53064648.0  53064648  53064648    10  0.0  ...  27.896361
44    622784.0    622784.0    622784    622784    10  0.0  ...   0.132784
45   1031274.0   1031274.0   1031274   1031274    10  0.0  ...   1.133230
46  17990592.0  17990592.0  17990592  17990592    10  0.0  ...   4.884601
47  64526577.0  64526577.0  64526577  64526577    10  0.0  ...   2.244388
48       128.0       128.0       128       128    10  0.0  ...  25.224170
49  17771013.0  17771013.0  17771013  17771013    10  0.0  ...   8.021804
50    622784.0    622784.0    622784    622784    10  0.0  ...   0.115203
51   1031274.0   1031274.0   1031274   1031274    10  0.0  ...   1.132388
52   6014528.0   6014528.0   6014528   6014528    10  0.0  ...   1.469344
53  21654211.0  21654211.0  21654211  21654211    10  0.0  ...   0.727165

                                     Cost                                  \
          max count       std        mean      median       min       max
0   88.024322    10  5.507188         0.0         0.0         0         0
1   40.315757    10  5.905834  48555234.0  48555234.0  48555234  48555234
2    0.164372    10  0.016478    622656.0    622656.0    622656    622656
3    1.473635    10  0.153182   1031274.0   1031274.0   1031274   1031274
4    9.525802    10  1.687004  16544632.0  16544632.0  16544632  16544632
5    6.584447    10  1.779211  58610340.0  58610340.0  58610340  58610340
6   16.437185    10  1.026793         0.0         0.0         0         0
7   13.702507    10  3.611687   9469746.0   9469746.0   9469746   9469746
8    0.174127    10  0.022278    622656.0    622656.0    622656    622656
9    1.490201    10  0.180318   1031274.0   1031274.0   1031274   1031274
10   1.914947    10  0.408816   3228168.0   3228168.0   3228168   3228168
11   1.255641    10  0.342575  11437647.0  11437647.0  11437647  11437647
12   1.240557    10  0.114923         0.0         0.0         0         0
13   0.441678    10  0.066550    624078.0    624078.0    624078    624078
14   0.064787    10  0.007931    210720.0    210720.0    210720    210720
15   0.498419    10  0.048849    349005.0    349005.0    349005    349005
16   0.108128    10  0.019852    210632.0    210632.0    210632    210632
17   0.067240    10  0.018027    749052.0    749052.0    749052    749052
18  19.126961    10  1.009108         0.0         0.0         0         0
19  12.053705    10  2.379966  10934586.0  10934586.0  10934586  10934586
20   0.167260    10  0.013759    622656.0    622656.0    622656    622656
21   1.542973    10  0.179764   1031274.0   1031274.0   1031274   1031274
22   2.257467    10  0.539548   3724736.0   3724736.0   3724736   3724736
23   1.430608    10  0.465720  13194532.0  13194532.0  13194532  13194532
24  50.491962    10  2.719044         0.0         0.0         0         0
25  21.674618    10  2.786130  29215368.0  29215368.0  29215368  29215368
26   0.173440    10  0.016478    622656.0    622656.0    622656    622656
27   1.547113    10  0.146122   1031274.0   1031274.0   1031274   1031274
28   4.692691    10  0.629755   9951520.0   9951520.0   9951520   9951520
29   3.047894    10  0.665879  35256299.0  35256299.0  35256299  35256299
30  71.757481    10  5.398503         0.0         0.0         0         0
31  32.032391    10  4.369532  37243323.0  37243323.0  37243323  37243323
32   0.186522    10  0.018089    622656.0    622656.0    622656    622656
33   1.565112    10  0.155725   1031274.0   1031274.0   1031274   1031274
34   7.499994    10  1.491703  12690688.0  12690688.0  12690688  12690688
35   4.294873    10  0.997543  44966269.0  44966269.0  44966269  44966269
36   2.830060    10  0.243630         0.0         0.0         0         0
37   2.885840    10  0.815822   1668186.0   1668186.0   1668186   1668186
38   0.157800    10  0.019502    562464.0    562464.0    562464    562464
39   1.344832    10  0.163525    931581.0    931581.0    931581    931581
40   0.282045    10  0.051114    562368.0    562368.0    562368    562368
41   0.104080    10  0.015903   1997605.0   1997605.0   1997605   1997605
42  95.110759    10  5.609148         0.0         0.0         0         0
43  44.891714    10  6.513035  53064648.0  53064648.0  53064648  53064648
44   0.185804    10  0.015986    622656.0    622656.0    622656    622656
45   1.585622    10  0.170500   1031274.0   1031274.0   1031274   1031274
46  10.381198    10  1.790216  17990464.0  17990464.0  17990464  17990464
47   6.767704    10  1.604723  64526577.0  64526577.0  64526577  64526577
48  30.628189    10  1.713384         0.0         0.0         0         0
49  20.904825    10  4.308146  17771013.0  17771013.0  17771013  17771013
50   0.178786    10  0.022225    622656.0    622656.0    622656    622656
51   1.617926    10  0.189628   1031274.0   1031274.0   1031274   1031274
52   4.341839    10  0.977428   6014400.0   6014400.0   6014400   6014400
53   2.332646    10  0.676625  21654211.0  21654211.0  21654211  21654211


   count  std
0     10  0.0
1     10  0.0
2     10  0.0
3     10  0.0
4     10  0.0
5     10  0.0
6     10  0.0
7     10  0.0
8     10  0.0
9     10  0.0
10    10  0.0
11    10  0.0
12    10  0.0
13    10  0.0
14    10  0.0
15    10  0.0
16    10  0.0
17    10  0.0
18    10  0.0
19    10  0.0
20    10  0.0
21    10  0.0
22    10  0.0
23    10  0.0
24    10  0.0
25    10  0.0
26    10  0.0
27    10  0.0
28    10  0.0
29    10  0.0
30    10  0.0
31    10  0.0
32    10  0.0
33    10  0.0
34    10  0.0
35    10  0.0
36    10  0.0
37    10  0.0
38    10  0.0
39    10  0.0
40    10  0.0
41    10  0.0
42    10  0.0
43    10  0.0
44    10  0.0
45    10  0.0
46    10  0.0
47    10  0.0
48    10  0.0
49    10  0.0
50    10  0.0
51    10  0.0
52    10  0.0
53    10  0.0

[54 rows x 22 columns]

In [19]:
df_agg.to_pickle('data/pre_measure_stat.pkl')

In [20]:
df_stat = pd.read_pickle(r"data/pre_measure_stat.pkl")

In [23]:
df_stat['Size']['mean']

0          128.0
1     48555234.0
2       622784.0
3      1031274.0
4     16544760.0
5     58610340.0
6          128.0
7      9469746.0
8       622784.0
9      1031274.0
10     3228296.0
11    11437647.0
12         128.0
13      624078.0
14      210848.0
15      349005.0
16      210760.0
17      749052.0
18         128.0
19    10934586.0
20      622784.0
21     1031274.0
22     3724864.0
23    13194532.0
24         128.0
25    29215368.0
26      622784.0
27     1031274.0
28     9951648.0
29    35256299.0
30         128.0
31    37243323.0
32      622784.0
33     1031274.0
34    12690816.0
35    44966269.0
36         128.0
37     1668186.0
38      562592.0
39      931581.0
40      562496.0
41     1997605.0
42         128.0
43    53064648.0
44      622784.0
45     1031274.0
46    17990592.0
47    64526577.0
48         128.0
49    17771013.0
50      622784.0
51     1031274.0
52     6014528.0
53    21654211.0
Name: mean, dtype: float64

In [26]:
Filename = df_stat['Filename']
Method = df_stat['Method']
Transformation = df_stat['Transformation']
Type = df_stat['Type']
Mean_Size = df_stat['Size']['mean']
Median_Size = df_stat['Size']['median']
Min_Size = df_stat['Size']['min']
Max_Size = df_stat['Size']['max']
Std_Size = df_stat['Size']['std']
Mean_Time = df_stat['Time']['mean']
Median_Time = df_stat['Time']['median']
Min_Time = df_stat['Time']['min']
Max_Time = df_stat['Time']['max']
Std_Time = df_stat['Time']['std']
Mean_Cost = df_stat['Cost']['mean']
Median_Cost = df_stat['Cost']['median']
Min_Cost = df_stat['Cost']['min']
Max_Cost = df_stat['Cost']['max']
Std_Cost = df_stat['Cost']['std']

In [27]:
dict = {'Filename': Filename, 'Method': Method, 'Transformation': Transformation, 
        'Type': Type, 'Mean_Size': Mean_Size, 'Median_Size': Median_Size, 
        'Min_Size': Min_Size, 'Max_Size': Max_Size, 'Std_Size': Std_Size, 
        'Mean_Time': Mean_Time, 'Median_Time': Median_Time, 'Min_Time': Min_Time, 
        'Max_Time': Max_Time, 'Std_Time': Std_Time, 'Mean_Cost': Mean_Cost, 
        'Median_Cost': Median_Cost, 'Min_Cost': Min_Cost, 'Max_Cost': Max_Cost, 
        'Std_Cost': Std_Cost}

In [28]:
df = pd.DataFrame(dict)

In [29]:
df

,Filename,Method,Transformation,Type,Mean_Size,Median_Size,Min_Size,Max_Size,Std_Size,Mean_Time,Median_Time,Min_Time,Max_Time,Std_Time,Mean_Cost,Median_Cost,Min_Cost,Max_Cost,Std_Cost
0,Anna_Karenina,Repetition Code,Decoding,.txt,128.0,128.0,128,128,0.0,77.840437,76.774378,69.430668,88.024322,5.507188,0.0,0.0,0,0,0.0
1,Anna_Karenina,Repetition Code,Encoding,.txt,48555234.0,48555234.0,48555234,48555234,0.0,31.607374,31.248659,24.537284,40.315757,5.905834,48555234.0,48555234.0,48555234,48555234,0.0
2,Anna_Karenina,Simple Code,Decoding,.txt,622784.0,622784.0,622784,622784,0.0,0.145694,0.148069,0.113236,0.164372,0.016478,622656.0,622656.0,622656,622656,0.0
3,Anna_Karenina,Simple Code,Encoding,.txt,1031274.0,1031274.0,1031274,1031274,0.0,1.269170,1.247905,1.086670,1.473635,0.153182,1031274.0,1031274.0,1031274,1031274,0.0
4,Anna_Karenina,XOR-Based Code,Decoding,.txt,16544760.0,16544760.0,16544760,16544760,0.0,6.117736,5.689381,4.151819,9.525802,1.687004,16544632.0,16544632.0,16544632,16544632,0.0
5,Anna_Karenina,XOR-Based Code,Encoding,.txt,58610340.0,58610340.0,58610340,58610340,0.0,3.285998,2.367637,2.004188,6.584447,1.779211,58610340.0,58610340.0,58610340,58610340,0.0
6,Around_the_World_in_Eighty_Days,Repetition Code,Decoding,.txt,128.0,128.0,128,128,0.0,14.756059,14.647059,13.505075,16.437185,1.026793,0.0,0.0,0,0,0.0
7,Around_the_World_in_Eighty_Days,Repetition Code,Encoding,.txt,9469746.0,9469746.0,9469746,9469746,0.0,7.468344,5.909235,3.853203,13.702507,3.611687,9469746.0,9469746.0,9469746,9469746,0.0
8,Around_the_World_in_Eighty_Days,Simple Code,Decoding,.txt,622784.0,622784.0,622784,622784,0.0,0.145943,0.143256,0.111720,0.174127,0.022278,622656.0,622656.0,622656,622656,0.0
9,Around_the_World_in_Eighty_Days,Simple Code,Encoding,.txt,1031274.0,1031274.0,1031274,1031274,0.0,1.267286,1.245431,1.054477,1.490201,0.180318,1031274.0,1031274.0,1031274,1031274,0.0
10,Around_the_World_in_Eighty_Days,XOR-Based Code,Decoding,.txt,3228296.0,3228296.0,3228296,3228296,0.0,1.473631,1.581491,0.817815,1.914947,0.408816,3228168.0,3228168.0,3228168,3228168,0.0
11,Around_the_World_in_Eighty_Days,XOR-Based Code,Encoding,.txt,11437647.0,11437647.0,11437647,11437647,0.0,0.817749,0.969391,0.394658,1.255641,0.342575,11437647.0,11437647.0,11437647,11437647,0.0
12,La_Jeunesse,Repetition Code,Decoding,.jpg,128.0,128.0,128,128,0.0,0.995391,0.961716,0.841397,1.240557,0.114923,0.0,0.0,0,0,0.0
13,La_Jeunesse,Repetition Code,Encoding,.jpg,624078.0,624078.0,624078,624078,0.0,0.336690,0.315723,0.270655,0.441678,0.066550,624078.0,624078.0,624078,624078,0.0
14,La_Jeunesse,Simple Code,Decoding,.jpg,210848.0,210848.0,210848,210848,0.0,0.051256,0.050518,0.040329,0.064787,0.007931,210720.0,210720.0,210720,210720,0.0
15,La_Jeunesse,Simple Code,Encoding,.jpg,349005.0,349005.0,349005,349005,0.0,0.419565,0.427707,0.349929,0.498419,0.048849,349005.0,349005.0,349005,349005,0.0
16,La_Jeunesse,XOR-Based Code,Decoding,.jpg,210760.0,210760.0,210760,210760,0.0,0.079253,0.084811,0.050033,0.108128,0.019852,210632.0,210632.0,210632,210632,0.0
17,La_Jeunesse,XOR-Based Code,Encoding,.jpg,749052.0,749052.0,749052,749052,0.0,0.041518,0.035054,0.019361,0.067240,0.018027,749052.0,749052.0,749052,749052,0.0
18,The_Picture_of_Dorian_Gray,Repetition Code,Decoding,.txt,128.0,128.0,128,128,0.0,17.400029,17.180545,16.093850,19.126961,1.009108,0.0,0.0,0,0,0.0
19,The_Picture_of_Dorian_Gray,Repetition Code,Encoding,.txt,10934586.0,10934586.0,10934586,10934586,0.0,7.277136,6.900356,4.800853,12.053705,2.379966,10934586.0,10934586.0,10934586,10934586,0.0
20,The_Picture_of_Dorian_Gray,Simple Code,Decoding,.txt,622784.0,622784.0,622784,622784,0.0,0.149017,0.151512,0.118998,0.167260,0.013759,622656.0,622656.0,622656,622656,0.0
21,The_Picture_of_Dorian_Gray,Simple Code,Encoding,.txt,1031274.0,1031274.0,1031274,1031274,0.0,1.256536,1.156910,1.094688,1.542973,0.179764,1031274.0,1031274.0,1031274,1031274,0.0
22,The_Picture_of_Dorian_Gray,XOR-Based Code,Decoding,.txt,3724864.0,3724864.0,3724864,3724864,0.0,1.506828,1.232886,0.997049,2.257467,0.539548,3724736.0,3724736.0,3724736,3724736,0.0
23,The_Picture_of_Dorian_Gray,XOR-Based Code,Encoding,.txt,13194532.0,13194532.0,13194532,13194532,0.0,0.822817,0.473197,0.439008,1.430608,0.465720,13194532.0,13194532.0,13194532,13194532,0.0
24,The_Republic_Plato,Repetition Code,Decoding,.txt,128.0,128.0,128,128,0.0,46.362251,45.558114,42.571362,50.491962,2.719044,0.0,0.0,0,0,0.0
25,The_Republic_Plato,Repetition Code,Encoding,.txt,29215368.0,29215368.0,29215368,29215368,0.0,17.039265,16.683977,13.913212,21.674618,2.786130,29215368.0,29215368.0,29215368,29215368,0.0
26,The_Republic_Plato,Simple Code,Decoding,.txt,622784.0,622784.0,622784,622784,0.0,0.154100,0.153208,0.132902,0.173440,0.016478,622656.0,622656.0,622656,622656,0.0
27,The_Republic_Plato,Simple Code,Encoding,.txt,1031274.0,1031274.0,1031274,1031274,0.0,1.260271,1.236617,1.087187,1.547113,0.146122,1031274.0,1031274.0,1031274,1031274,0.0
28,The_Republic_Plato,XOR-Based Code,Decoding,.txt,9951648.0,9951648.0,9951648,9951648,0.0,3.646704,3.482655,2.637422,4.692691,0.629755,9951520.0,9951520.0,9951520,9951520,0.0
29,The_Republic_Plato,XOR-Based Code,Encoding,.txt,35256299.0,35256299.0,35256299,35256299,0.0,1.624269,1.317596,1.167554,3.047894,0.665879,35256299.0,35256299.0,35256299,35256299,0.0
30,Ulysses,Repetition Code,Decoding,.txt,128.0,128.0,128,128,0.0,61.595433,63.043663,54.849316,71.757481,5.398503,0.0,0.0,0,0,0.0
31,Ulysses,Repetition Code,Encoding,.txt,37243323.0,37243323.0,37243323,37243323,0.0,23.091148,21.742941,18.672860,32.032391,4.369532,37243323.0,37243323.0,37243323,37243323,0.0
32,Ulysses,Simple Code,Decoding,.txt,622784.0,622784.0,622784,622784,0.0,0.160736,0.155265,0.140861,0.186522,0.018089,622656.0,622656.0,622656,622656,0.0
33,Ulysses,Simple Code,Encoding,.txt,1031274.0,1031274.0,1031274,1031274,0.0,1.288431,1.226764,1.071071,1.565112,0.155725,1031274.0,1031274.0,1031274,1031274,0.0
34,Ulysses,XOR-Based Code,Decoding,.txt,12690816.0,12690816.0,12690816,12690816,0.0,4.759035,4.487206,3.225348,7.499994,1.491703,12690688.0,12690688.0,12690688,12690688,0.0
35,Ulysses,XOR-Based Code,Encoding,.txt,44966269.0,44966269.0,44966269,44966269,0.0,2.339750,1.854134,1.498061,4.294873,0.997543,44966269.0,44966269.0,44966269,44966269,0.0
36,Vue_de_la_Buena_Vista,Repetition Code,Decoding,.jpg,128.0,128.0,128,128,0.0,2.435162,2.472652,2.039240,2.830060,0.243630,0.0,0.0,0,0,0.0
37,Vue_de_la_Buena_Vista,Repetition Code,Encoding,.jpg,1668186.0,1668186.0,1668186,1668186,0.0,1.617927,1.543016,0.691113,2.885840,0.815822,1668186.0,1668186.0,1668186,1668186,0.0
38,Vue_de_la_Buena_Vista,Simple Code,Decoding,.jpg,562592.0,562592.0,562592,562592,0.0,0.130026,0.137809,0.092820,0.157800,0.019502,562464.0,562464.0,562464,562464,0.0
39,Vue_de_la_Buena_Vista,Simple Code,Encoding,.jpg,931581.0,931581.0,931581,931581,0.0,1.131019,1.108792,0.928043,1.344832,0.163525,931581.0,931581.0,931581,931581,0.0
40,Vue_de_la_Buena_Vista,XOR-Based Code,Decoding,.jpg,562496.0,562496.0,562496,562496,0.0,0.199052,0.194732,0.117583,0.282045,0.051114,562368.0,562368.0,562368,562368,0.0
41,Vue_de_la_Buena_Vista,XOR-Based Code,Encoding,.jpg,1997605.0,1997605.0,1997605,1997605,0.0,0.072204,0.069056,0.050924,0.104080,0.015903,1997605.0,1997605.0,1997605,1997605,0.0
42,bbc_house,Repetition Code,Decoding,.wav,128.0,128.0,128,128,0.0,84.954221,83.913800,75.872247,95.110759,5.609148,0.0,0.0,0,0,0.0
43,bbc_house,Repetition Code,Encoding,.wav,53064648.0,53064648.0,53064648,53064648,0.0,35.077039,32.671307,27.896361,44.891714,6.513035,53064648.0,53064648.0,53064648,53064648,0.0
44,bbc_house,Simple Code,Decoding,.wav,622784.0,622784.0,622784,622784,0.0,0.154401,0.153800,0.132784,0.185804,0.015986,622656.0,622656.0,622656,622656,0.0
45,bbc_house,Simple Code,Encoding,.wav,1031274.0,1031274.0,1031274,1031274,0.0,1.323869,1.273211,1.133230,1.585622,0.170500,1031274.0,1031274.0,1031274,1031274,0.0
46,bbc_house,XOR-Based Code,Decoding,.wav,17990592.0,17990592.0,17990592,17990592,0.0,6.943856,6.537761,4.884601,10.381198,1.790216,17990464.0,17990464.0,17990464,17990464,0.0
47,bbc_house,XOR-Based Code,Encoding,.wav,64526577.0,64526577.0,64526577,64526577,0.0,3.628981,2.681093,2.244388,6.767704,1.604723,64526577.0,64526577.0,64526577,64526577,0.0
48,bbc_peregrine_falcon,Repetition Code,Decoding,.wav,128.0,128.0,128,128,0.0,28.076092,27.686002,25.224170,30.628189,1.713384,0.0,0.0,0,0,0.0
49,bbc_peregrine_falcon,Repetition Code,Encoding,.wav,17771013.0,17771013.0,17771013,17771013,0.0,12.444221,11.482200,8.021804,20.904825,4.308146,17771013.0,17771013.0,17771013,17771013,0.0
50,bbc_peregrine_falcon,Simple Code,Decoding,.wav,622784.0,622784.0,622784,622784,0.0,0.153826,0.161609,0.115203,0.178786,0.022225,622656.0,622656.0,622656,622656,0.0
51,bbc_peregrine_falcon,Simple Code,Encoding,.wav,1031274.0,1031274.0,1031274,1031274,0.0,1.326413,1.298124,1.132388,1.617926,0.189628,1031274.0,1031274.0,1031274,1031274,0.0
52,bbc_peregrine_falcon,XOR-Based Code,Decoding,.wav,6014528.0,6014528.0,6014528,6014528,0.0,2.303345,1.913427,1.469344,4.341839,0.977428,6014400.0,6014400.0,6014400,6014400,0.0
53,bbc_peregrine_falcon,XOR-Based Code,Encoding,.wav,21654211.0,21654211.0,21654211,21654211,0.0,1.301459,0.934893,0.727165,2.332646,0.676625,21654211.0,21654211.0,21654211,21654211,0.0

In [31]:
df.to_pickle('data/pre_measure_stat.pkl')